import { randomUUID } from 'node:crypto';
import { isSensitiveKey, sanitizeForReview, sanitizeText } from './redaction.js';
import { validateEvidenceRecord } from './evidence.js';
import type { ExecutionMode, ProviderSpikeEvidence, ProviderSpikeExecutionContext, ProviderSpikeRunOptions, ProviderSpikeRunResult, ProviderSpikeTestCase, ProviderTransportResponse, SanitizedValue, SpikeResult } from './types.js';

const DEFAULT_TIMEOUT_MS=1000, DEFAULT_MAX_REQUESTS=1;
const DEFAULT_SAFE_HEADERS=['content-type','retry-after','x-request-id','x-correlation-id','x-ratelimit-limit','x-ratelimit-remaining','x-ratelimit-reset'] as const;
class BlockedError extends Error{constructor(readonly category:string,message:string){super(message);this.name='BlockedError';}}
class TimeoutError extends BlockedError{constructor(ms:number){super('TIMEOUT',`Transport timed out after ${ms}ms.`);}}
class RequestLimitError extends BlockedError{constructor(n:number){super('REQUEST_LIMIT_EXCEEDED',`Request limit of ${n} reached before transport execution.`);}}
function pos(v:number|undefined){return v!==undefined&&Number.isInteger(v)&&v>0;}
function nonNegativeFinite(v:unknown):v is number{return typeof v==='number'&&Number.isFinite(v)&&v>=0;}
function statusCategory(s:number|string|undefined){if(typeof s!=='number')return null;if(s===429)return 'HTTP_429';if(s>=400&&s<500)return 'HTTP_4XX';if(s>=500&&s<600)return 'HTTP_5XX';return null;}
function validateConfig(t:ProviderSpikeTestCase){for(const [k,v] of [['testId',t.testId],['provider',t.provider],['capability',t.capability],['providerEnvironment',t.providerEnvironment]] as const)if(!v?.trim())throw new BlockedError('INVALID_TEST_CONFIGURATION',`${k} must be a non-empty string.`);const runtimeMode=(t as {mode?:unknown}).mode;if(runtimeMode!==undefined&&runtimeMode!=='offline'&&runtimeMode!=='live')throw new BlockedError('INVALID_TEST_CONFIGURATION','mode must be offline or live.');if(t.timeoutMs!==undefined&&!pos(t.timeoutMs))throw new BlockedError('INVALID_TEST_CONFIGURATION','timeoutMs must be positive.');if(t.maxRequests!==undefined&&!pos(t.maxRequests))throw new BlockedError('INVALID_TEST_CONFIGURATION','maxRequests must be positive.');}
function secretsFor(t:ProviderSpikeTestCase,env:NodeJS.ProcessEnv,extra:readonly string[]){const s=[...extra];for(const n of t.requiredCredentialEnvVars??[])if(env[n])s.push(env[n]!);return [...new Set(s.filter(Boolean))];}
function validateLive(t:ProviderSpikeTestCase,o:ProviderSpikeRunOptions,env:NodeJS.ProcessEnv){if((t.mode??'offline')!=='live')return;if(t.liveSafety?.enabled!==true)throw new BlockedError('LIVE_SAFETY_MISSING','Live execution requires explicit opt-in.');if(!pos(t.timeoutMs)||!pos(t.maxRequests))throw new BlockedError('LIVE_SAFETY_MISSING','Live execution requires explicit timeout and request cap.');const creds=t.requiredCredentialEnvVars??[];if(!creds.length)throw new BlockedError('LIVE_CREDENTIAL_CONFIGURATION_MISSING','Live execution requires credential env names.');for(const n of creds)if(!env[n])throw new BlockedError('MISSING_LIVE_CREDENTIAL',`Required credential ${n} is not available.`);if(o.transport?.kind!=='live')throw new BlockedError('LIVE_TRANSPORT_MISSING','Live execution requires live transport.');if(t.mayIncurCost){const cap=t.liveSafety.maxDevelopmentCostUsd,est=t.liveSafety.estimatedRunCostUsd;if(!nonNegativeFinite(cap)||!nonNegativeFinite(est))throw new BlockedError('COST_SAFETY_CONFIGURATION_MISSING','Cost-bearing live test requires finite non-negative cost cap and estimate.');if(est>cap)throw new BlockedError('COST_SAFETY_REJECTED','Estimated run cost exceeds development cost ceiling.');}if(t.requiresTokenLimits){const x=t.liveSafety.tokenLimits;if(!x||!pos(x.maxInputTokens)||!pos(x.maxOutputTokens))throw new BlockedError('TOKEN_LIMIT_CONFIGURATION_MISSING','Token limits required.');}}
async function withTimeout(ms:number,fn:(signal:AbortSignal)=>Promise<ProviderTransportResponse>){const c=new AbortController();let timer:NodeJS.Timeout|undefined;try{return await Promise.race([fn(c.signal),new Promise<never>((_,reject)=>{timer=setTimeout(()=>{c.abort();reject(new TimeoutError(ms));},ms);})]);}finally{if(timer)clearTimeout(timer);}}
function validateResponse(r:unknown):asserts r is ProviderTransportResponse{if(typeof r!=='object'||r===null||Array.isArray(r))throw new BlockedError('MALFORMED_PROVIDER_RESPONSE','Provider response must be object.');const x=r as ProviderTransportResponse;if(x.status!==undefined&&typeof x.status!=='number'&&typeof x.status!=='string')throw new BlockedError('MALFORMED_PROVIDER_RESPONSE','Invalid provider status.');}
function safeHeaders(t:ProviderSpikeTestCase,r:ProviderTransportResponse|undefined,secrets:readonly string[]){const allowed=new Set((t.safeResponseHeaders??DEFAULT_SAFE_HEADERS).map(x=>x.toLowerCase()).filter(x=>!isSensitiveKey(x)&&x!=='set-cookie'));const out:Record<string,string>={};for(const [k,v] of Object.entries(r?.headers??{})){const n=k.toLowerCase();if(v!==undefined&&allowed.has(n))out[n]=sanitizeText(v,secrets);}return out;}
function exitCode(r:SpikeResult):0|1|2{return r==='PASS'?0:r==='FAIL'?1:2;}

export async function runProviderSpikeCase(testCase:ProviderSpikeTestCase,options:ProviderSpikeRunOptions={}):Promise<ProviderSpikeRunResult>{
 const start=Date.now(), runtimeMode=(testCase as {mode?:unknown}).mode??'offline', mode:ExecutionMode=runtimeMode==='live'?'live':'offline', timeout=testCase.timeoutMs??DEFAULT_TIMEOUT_MS, max=testCase.maxRequests??DEFAULT_MAX_REQUESTS, env=options.env??process.env, secrets=secretsFor(testCase,env,options.redactionSecrets??[]), reqMeta:SanitizedValue[]=[], notes=[...(testCase.notes??[])].map(x=>sanitizeText(x,secrets));
 let count=0,last:ProviderTransportResponse|undefined,reqId:string|undefined,result:SpikeResult='BLOCKED',category:string|null=null,errorOutput:string|null=null;
 const context:ProviderSpikeExecutionContext={mode,testConfig:testCase.testConfig??{},request:async(request)=>{if(count>=max)throw new RequestLimitError(max);if(!options.transport)throw new BlockedError('TRANSPORT_UNAVAILABLE','No transport provided.');if(mode==='offline'&&options.transport.kind!=='mock')throw new BlockedError('LIVE_TRANSPORT_BLOCKED','Offline mode rejects live transport.');count++;reqMeta.push(sanitizeForReview({sequence:count,method:request.method??null,metadata:request.safeMetadata??null},secrets));let response:ProviderTransportResponse;try{response=await withTimeout(timeout,s=>options.transport!.send(request,{signal:s}));}catch(e){if(e instanceof BlockedError)throw e;throw new BlockedError('NETWORK_ERROR',sanitizeText(e,secrets));}validateResponse(response);last=response;if(testCase.requestIdExtractor){try{const x=testCase.requestIdExtractor(response);reqId=x?sanitizeText(x,secrets):undefined;}catch(e){notes.push(`Provider request ID extraction failed: ${sanitizeText(e,secrets)}`);}}return response;}};
 try{validateConfig(testCase);validateLive(testCase,options,env);if(testCase.prerequisite){const p=await testCase.prerequisite();if(!p.ok)throw new BlockedError('PREREQUISITE_MISSING',p.reason??'Prerequisite unavailable.');}const observation=await testCase.execute(context);let ok=false;try{ok=await testCase.assert(observation,context);}catch(e){result='FAIL';category=statusCategory(last?.status)??'ASSERTION_ERROR';errorOutput=sanitizeText(e,secrets);}if(!errorOutput){result=ok?'PASS':'FAIL';category=statusCategory(last?.status)??(ok?null:'ASSERTION_FAILED');if(!ok)notes.push('Defined assertion did not pass.');}}
 catch(e){result='BLOCKED';category=e instanceof BlockedError?e.category:'HARNESS_EXECUTION_ERROR';errorOutput=sanitizeText(e instanceof Error?e.message:e,secrets);if(errorOutput)notes.push(errorOutput);}
 let evidence=validateEvidenceRecord(sanitizeForReview({run_id:randomUUID(),test_id:testCase.testId||'INVALID_TEST_ID',provider:testCase.provider||'UNKNOWN_PROVIDER',capability:testCase.capability||'UNKNOWN_CAPABILITY',timestamp:new Date().toISOString(),provider_environment:testCase.providerEnvironment||'UNKNOWN_ENVIRONMENT',safe_request_metadata:reqMeta,provider_status:last?.status??null,safe_response_headers:safeHeaders(testCase,last,secrets),provider_request_id:reqId??null,latency_ms:Math.max(0,Date.now()-start),result,error_category:category,notes,request_count:count,execution_mode:mode,test_case_version:testCase.version??null},secrets));
 const fallback=(x:ProviderSpikeEvidence)=>JSON.stringify(x,null,2);let serialized='';try{serialized=sanitizeText((options.serializer??fallback)(evidence),secrets);}catch(e){evidence=validateEvidenceRecord(sanitizeForReview({...evidence,result:'BLOCKED',error_category:'EVIDENCE_SERIALIZATION_FAILED',notes:[...evidence.notes,`Evidence serialization failed: ${sanitizeText(e,secrets)}`]},secrets));serialized=fallback(evidence);errorOutput=sanitizeText(e,secrets);}if(options.evidenceWriter){try{await options.evidenceWriter(serialized,evidence);}catch(e){evidence=validateEvidenceRecord(sanitizeForReview({...evidence,result:'BLOCKED',error_category:'EVIDENCE_WRITE_FAILED',notes:[...evidence.notes,`Evidence write failed: ${sanitizeText(e,secrets)}`]},secrets));serialized=fallback(evidence);errorOutput=sanitizeText(e,secrets);}}
 const summary=sanitizeText(`[${evidence.result}] ${evidence.test_id} run=${evidence.run_id} provider=${evidence.provider} capability=${evidence.capability} mode=${evidence.execution_mode} requests=${evidence.request_count} status=${evidence.provider_status??'n/a'} request_id=${evidence.provider_request_id??'n/a'} error=${evidence.error_category??'none'}`,secrets);
 return {exitCode:exitCode(evidence.result),summary,machineReadableEvidence:serialized,evidence,errorOutput:errorOutput?sanitizeText(errorOutput,secrets):null};
}

export class ProviderSpikeRegistry{private readonly cases=new Map<string,ProviderSpikeTestCase>();register(t:ProviderSpikeTestCase){if(!t.testId||this.cases.has(t.testId))throw new Error(`Provider Spike test_id must be unique and non-empty: ${t.testId||'<empty>'}`);this.cases.set(t.testId,t);}get(id:string){return this.cases.get(id);}async run(id:string,o:ProviderSpikeRunOptions={}){const t=this.cases.get(id);if(!t)throw new Error(`Provider Spike test_id is not registered: ${id}`);return runProviderSpikeCase(t,o);}}
