import { randomUUID } from 'node:crypto';
import { blockProviderSpike, runProviderSpikeCase } from './harness.js';
import { createP1T02TeamPreflightCase, createZernioLiveTransport, P1_T02_PROFILE_A_RECORDED_ID } from './p1-t02-zernio.js';
import type { ProviderSpikeExecutionContext, ProviderSpikeRunResult, ProviderSpikeTestCase, ProviderTransport, ProviderTransportResponse } from './types.js';

const SAFE_HEADERS=['content-type','retry-after','x-request-id','x-correlation-id','x-ratelimit-limit','x-ratelimit-remaining','x-ratelimit-reset','idempotent-replayed'] as const;
export const P1_T04_PROFILE_ID=P1_T02_PROFILE_A_RECORDED_ID;
export const P1_T04_ACCOUNT_ID='6ac64f8740364f4695dd3077';
export const P1_T04_PAGE_ID='1387424501114639';
export const P1_T04_PAGE_NAME='Clothing Brand';
export const P1_T04_NORMAL_REQUEST_CEILING=22;
export const P1_T04_CLEANUP_REQUEST_ALLOWANCE=6;
const EXPIRY_DAYS=1;
const TIMEZONE='Africa/Cairo';
type JsonObject=Record<string,unknown>;
type PostKind='draft'|'scheduled'|'immediate';
type Result='PASS'|'FAIL'|'BLOCKED';
interface Counter{normal:number;cleanup:number;normalMax:number;cleanupMax:number;}
interface CreatedKeyInternal{metadata:P1T04KeyMetadata;secret:string;}
interface ArtifactState{draftId:string|null;scheduledId:string|null;publicId:string|null;}

export interface P1T04KeyMetadata{providerKeyId:string;syntheticName:string;scope:'profiles';permittedProfileId:string;permission:'read-write';expiresAt:string;creationStatus:number|null;creationRequestId:string|null;}
export interface P1T04TargetEvidence{accountId:string|null;platform:string|null;profileId:string|null;pageId:string|null;pageName:string|null;pageMatch:boolean;healthStatus:string|null;canPost:boolean;accountRequestId:string|null;pageRequestId:string|null;healthRequestId:string|null;}
export interface P1T04PostEvidence{kind:PostKind;postId:string|null;createStatus:number|null;createRequestId:string|null;readStatus:number|null;readRequestId:string|null;replayStatus:number|null;replayRequestId:string|null;sameLogicalPost:boolean|null;duplicate:boolean;scheduledRequested:string|null;scheduledReturned:string|null;platformPostId:string|null;publicUrl:string|null;publishedAt:string|null;cleanupConfirmed:boolean;cleanupStatus:number|null;cleanupRequestId:string|null;cleanupReadStatus:number|null;cleanupReadRequestId:string|null;}
export interface P1T04KeyCleanup{revokeStatus:number|null;revokeRequestId:string|null;revokedKeyValid:boolean|null;verifyStatus:number|null;verifyRequestId:string|null;confirmed:boolean;}
export interface P1T04StepEvidence{testId:string;runId:string;timestamp:string;result:Result;status:number|string|null;requestId:string|null;latencyMs:number;errorCategory:string|null;requestCount:number;}
export interface P1T04RunResult{liveEnabled:boolean;result:Result;errorCategory:string|null;identityMatch:boolean;preflight:ProviderSpikeRunResult|null;key:P1T04KeyMetadata|null;target:P1T04TargetEvidence|null;draft:P1T04PostEvidence|null;scheduled:P1T04PostEvidence|null;immediate:P1T04PostEvidence|null;keyCleanup:P1T04KeyCleanup|null;wrongTargetObserved:boolean;duplicateConfirmedPublishObserved:boolean;normalRequestCount:number;cleanupRequestCount:number;liveRequestCount:number;steps:P1T04StepEvidence[];}
export interface P1T04RunOptions{live?:boolean;env?:NodeJS.ProcessEnv;providerEnvironment?:string;controlTransport?:ProviderTransport;scopedTransportFactory?:(secret:string)=>ProviderTransport;runTag?:string;normalRequestCeiling?:number;cleanupRequestAllowance?:number;now?:Date;sleep?:(ms:number)=>Promise<void>;}

function obj(value:unknown):JsonObject|null{return typeof value==='object'&&value!==null&&!Array.isArray(value)?value as JsonObject:null;}
function status(response:ProviderTransportResponse){return typeof response.status==='number'?response.status:null;}
function header(response:ProviderTransportResponse,name:string){const target=name.toLowerCase();for(const [key,value] of Object.entries(response.headers??{}))if(key.toLowerCase()===target&&value)return value;return undefined;}
function requestId(response:ProviderTransportResponse){return header(response,'x-request-id')??header(response,'x-correlation-id')??null;}
function errorCategory(error:unknown){return obj(error)?.category as string|undefined;}
function valueId(value:unknown):string|null{if(typeof value==='string'&&value)return value;const o=obj(value);if(!o)return null;const v=o._id??o.id??o.accountId;return typeof v==='string'&&v?v:null;}
function validExpiry(value:unknown){if(typeof value!=='string'||!value)return null;return Number.isFinite(Date.parse(value))?value:null;}
function normalizeProfileId(value:unknown){return valueId(value);}
function redactionSecrets(env:NodeJS.ProcessEnv,extra:readonly string[]=[]){const out=[...extra];if(env.ZERNIO_EXPECTED_USER_EMAIL)out.push(env.ZERNIO_EXPECTED_USER_EMAIL);return [...new Set(out.filter(Boolean))];}
function scopedEnv(secret:string):NodeJS.ProcessEnv{return {P1_T04_SCOPED_KEY_RUNTIME:secret};}
function step(run:ProviderSpikeRunResult):P1T04StepEvidence{return {testId:run.evidence.test_id,runId:run.evidence.run_id,timestamp:run.evidence.timestamp,result:run.evidence.result,status:run.evidence.provider_status,requestId:run.evidence.provider_request_id,latencyMs:run.evidence.latency_ms,errorCategory:run.evidence.error_category,requestCount:run.evidence.request_count};}
function isTransient(error:unknown){const c=errorCategory(error);return c==='TIMEOUT'||c==='NETWORK_ERROR';}
function rateOrAuth(response:ProviderTransportResponse,operation:string){const s=status(response);if(s===429)blockProviderSpike('PROVIDER_RATE_LIMITED',`${operation} was rate limited.`);if(s===401||s===403)blockProviderSpike('PROVIDER_AUTHORIZATION_BLOCKED',`${operation} was not authorized.`);}
function ensureStatus(response:ProviderTransportResponse,allowed:readonly number[],operation:string){rateOrAuth(response,operation);const s=status(response);if(s!==null&&s>=500)blockProviderSpike('PROVIDER_5XX_BLOCKED',`${operation} returned provider 5xx.`);if(s===null||!allowed.includes(s))blockProviderSpike('PROVIDER_HTTP_BLOCKED',`${operation} returned unexpected status ${String(response.status)}.`);return s;}
function safeMetaPhase(request:{safeMetadata?:unknown}){return obj(request.safeMetadata)?.phase==='cleanup'?'cleanup':'normal';}
function bounded(transport:ProviderTransport,counter:Counter,forceCleanup=false):ProviderTransport{return {kind:transport.kind,send:async(request,context)=>{const cleanup=forceCleanup||safeMetaPhase(request)==='cleanup';if(cleanup){if(counter.cleanup>=counter.cleanupMax)blockProviderSpike('CLEANUP_REQUEST_LIMIT_EXCEEDED',`P1-T04 cleanup allowance of ${counter.cleanupMax} reached.`);counter.cleanup++;}else{if(counter.normal>=counter.normalMax)blockProviderSpike('REQUEST_LIMIT_EXCEEDED',`P1-T04 normal request ceiling of ${counter.normalMax} reached.`);counter.normal++;}return transport.send(request,context);}};}
function commonCase(testId:string,maxRequests:number,requiredCredentialEnvVars:readonly string[],providerEnvironment:string):ProviderSpikeTestCase{return {testId,provider:'Zernio',capability:'Publishing',providerEnvironment,mode:'live',timeoutMs:7000,maxRequests,requiredCredentialEnvVars,liveSafety:{enabled:true},safeResponseHeaders:SAFE_HEADERS,requestIdExtractor:r=>requestId(r)??undefined,execute:async()=>({ok:true}),assert:async()=>true};}
async function runCase(testId:string,maxRequests:number,requiredCredentialEnvVars:readonly string[],providerEnvironment:string,env:NodeJS.ProcessEnv,transport:ProviderTransport,secrets:readonly string[],execute:(context:ProviderSpikeExecutionContext)=>Promise<unknown>,assert:(observation:unknown)=>boolean|Promise<boolean>){const base=commonCase(testId,maxRequests,requiredCredentialEnvVars,providerEnvironment);return runProviderSpikeCase({...base,execute,assert:async observation=>assert(observation)},{env,transport,redactionSecrets:redactionSecrets(env,secrets)});}

function parseApiKeys(body:unknown){const root=obj(body);if(!root||!Array.isArray(root.apiKeys))blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','API key list response is missing apiKeys array.');return root.apiKeys.map(obj).filter((x):x is JsonObject=>Boolean(x));}
async function reconcileCreatedKeyForCleanup(context:ProviderSpikeExecutionContext,syntheticName:string,mode:'unknown'|'malformed'){
 const list=await context.request({method:'GET',url:'/v1/api-keys',safeMetadata:{path:'/v1/api-keys',method:'GET',purpose:`${mode}-create-exact-name-reconciliation`,synthetic_name:syntheticName,phase:mode==='malformed'?'cleanup':'normal'}});
 if(status(list)!==200){if(mode==='malformed')blockProviderSpike('PUBLISHING_KEY_CLEANUP_UNCONFIRMED','Malformed successful key create could not be reconciled.');ensureStatus(list,[200],'Publishing-key reconciliation');}
 let listed:JsonObject[];try{listed=parseApiKeys(list.body);}catch(error){if(mode==='malformed')blockProviderSpike('PUBLISHING_KEY_CLEANUP_UNCONFIRMED','Malformed successful key create returned invalid reconciliation data.');throw error;}
 const matches=listed.filter(k=>k.name===syntheticName);if(matches.length>1)blockProviderSpike('AMBIGUOUS_SCOPED_KEY_STATE','Multiple exact-name publishing keys found during reconciliation.');if(matches.length===0){if(mode==='malformed')blockProviderSpike('PUBLISHING_KEY_CLEANUP_UNCONFIRMED','Malformed successful key create could not be reconciled to one exact key.');blockProviderSpike('UNKNOWN_SCOPED_KEY_CREATE_OUTCOME','Publishing key creation outcome remained uncertain.');}
 const id=valueId(matches[0]);if(!id){if(mode==='malformed')blockProviderSpike('PUBLISHING_KEY_CLEANUP_UNCONFIRMED','Reconciled publishing key is missing provider ID.');blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Reconciled publishing key is missing provider ID.');}
 const revoked=await context.request({method:'DELETE',url:`/v1/api-keys/${encodeURIComponent(id)}`,safeMetadata:{path:'/v1/api-keys/{keyId}',method:'DELETE',purpose:'reconciled-publishing-key-cleanup',provider_key_id:id,phase:'cleanup'}});if(status(revoked)!==200)blockProviderSpike('PUBLISHING_KEY_CLEANUP_UNCONFIRMED','Reconciled publishing key cleanup was not confirmed.');
 blockProviderSpike(mode==='malformed'?'MALFORMED_PROVIDER_RESPONSE':'UNKNOWN_SCOPED_KEY_CREATE_OUTCOME',mode==='malformed'?'Malformed publishing key response was reconciled and revoked.':'Publishing key create remained uncertain after safe reconciliation.');
}
async function createPublishingKey(context:ProviderSpikeExecutionContext,syntheticName:string,capture:(key:CreatedKeyInternal)=>void){
 let response:ProviderTransportResponse;try{response=await context.request({method:'POST',url:'/v1/api-keys',body:{name:syntheticName,expiresIn:EXPIRY_DAYS,scope:'profiles',profileIds:[P1_T04_PROFILE_ID],permission:'read-write'},safeMetadata:{path:'/v1/api-keys',method:'POST',synthetic_name:syntheticName,scope:'profiles',profile_id:P1_T04_PROFILE_ID,permission:'read-write',expires_in_days:1}});}catch(error){if(isTransient(error))return reconcileCreatedKeyForCleanup(context,syntheticName,'unknown');throw error;}
 const s=status(response);if(s!==201){if(s!==null&&s>=500)return reconcileCreatedKeyForCleanup(context,syntheticName,'unknown');rateOrAuth(response,'Temporary publishing-key create');blockProviderSpike('PROVIDER_HTTP_BLOCKED',`Temporary publishing-key create returned ${String(response.status)}.`);}
 const root=obj(response.body),apiKey=obj(root?.apiKey);if(!apiKey)return reconcileCreatedKeyForCleanup(context,syntheticName,'malformed');const providerKeyId=valueId(apiKey);if(!providerKeyId)return reconcileCreatedKeyForCleanup(context,syntheticName,'malformed');
 const secret=typeof apiKey.key==='string'&&apiKey.key?apiKey.key:null,ids=Array.isArray(apiKey.profileIds)?apiKey.profileIds.map(normalizeProfileId):null,expiresAt=validExpiry(apiKey.expiresAt);const semantics=secret&&apiKey.name===syntheticName&&apiKey.scope==='profiles'&&apiKey.permission==='read-write'&&ids?.length===1&&ids[0]===P1_T04_PROFILE_ID&&expiresAt;
 if(!semantics){const cleanup=await context.request({method:'DELETE',url:`/v1/api-keys/${encodeURIComponent(providerKeyId)}`,safeMetadata:{path:'/v1/api-keys/{keyId}',method:'DELETE',purpose:'malformed-publishing-key-cleanup',provider_key_id:providerKeyId,phase:'cleanup'}});if(status(cleanup)!==200)blockProviderSpike('PUBLISHING_KEY_CLEANUP_UNCONFIRMED','Malformed publishing-key cleanup was not confirmed.');blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Publishing-key response does not match requested restricted write scope.');}
 const metadata:P1T04KeyMetadata={providerKeyId,syntheticName,scope:'profiles',permittedProfileId:P1_T04_PROFILE_ID,permission:'read-write',expiresAt:expiresAt!,creationStatus:s,creationRequestId:requestId(response)};capture({metadata,secret:secret!});return {ok:true};
}

function parseAccounts(body:unknown){const root=obj(body);if(!root||!Array.isArray(root.accounts))blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Account list response is missing accounts array.');return root.accounts.map(obj).filter((x):x is JsonObject=>Boolean(x));}
function parsePages(body:unknown){const root=obj(body);if(!root||!Array.isArray(root.pages))blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Facebook Page response is missing pages array.');return {root,pages:root.pages.map(obj).filter((x):x is JsonObject=>Boolean(x))};}
function accountProfileId(account:JsonObject){return normalizeProfileId(account.profileId??account.profile);}
function targetAccount(body:unknown){const accounts=parseAccounts(body),exact=accounts.filter(a=>valueId(a)===P1_T04_ACCOUNT_ID);if(exact.length===0)blockProviderSpike('EXPECTED_PUBLISHING_ACCOUNT_NOT_FOUND','Expected frozen Facebook publishing account was not found.');if(exact.length>1)blockProviderSpike('AMBIGUOUS_PUBLISHING_ACCOUNT_STATE','Expected publishing account appeared more than once.');const account=exact[0]!,platform=typeof account.platform==='string'?account.platform:null,profileId=accountProfileId(account);return {account,platform,profileId};}
function platformEntry(post:JsonObject){if(!Array.isArray(post.platforms))return null;const entries=post.platforms.map(obj).filter((x):x is JsonObject=>Boolean(x)).filter(x=>x.platform==='facebook');return entries.length===1?entries[0]!:null;}
function postEnvelope(body:unknown){const root=obj(body);const post=obj(root?.post)??obj(root?.existingPost);return post;}
function postPageId(entry:JsonObject|null){if(!entry)return null;const direct=entry.pageId;if(typeof direct==='string'&&direct)return direct;const psd=obj(entry.platformSpecificData);return typeof psd?.pageId==='string'?psd.pageId:null;}
function postAccountId(entry:JsonObject|null){return entry?valueId(entry.accountId):null;}
function postId(post:JsonObject|null){return post?valueId(post):null;}
function postState(post:JsonObject|null){return typeof post?.status==='string'?post.status:null;}
function content(post:JsonObject|null){return typeof post?.content==='string'?post.content:null;}
function platformState(entry:JsonObject|null){return typeof entry?.status==='string'?entry.status:null;}
function facebookPageFromPlatformPostId(value:unknown){if(typeof value!=='string'||!value)return null;const match=value.match(/^([1-9]\d*)_([1-9]\d*)$/);return match?.[1]??null;}
function facebookPageFromPublicUrl(value:unknown){if(typeof value!=='string'||!value)return null;try{const url=new URL(value);if(url.protocol!=='https:'||!['facebook.com','www.facebook.com'].includes(url.hostname.toLowerCase())||url.search||url.hash)return null;const parts=url.pathname.split('/').filter(Boolean);if(parts.length!==1)return null;return facebookPageFromPlatformPostId(parts[0]);}catch{return null;}}
function alternateImmediatePageAttestation(entry:JsonObject){const rawPostId=entry.platformPostId,rawUrl=entry.platformPostUrl;const hasPostId=typeof rawPostId==='string'&&rawPostId.length>0,hasUrl=typeof rawUrl==='string'&&rawUrl.length>0;const fromPostId=facebookPageFromPlatformPostId(rawPostId),fromUrl=facebookPageFromPublicUrl(rawUrl);if((hasPostId&&!fromPostId)||(hasUrl&&!fromUrl))return {pageId:null,critical:false,unconfirmed:true};const ids=[fromPostId,fromUrl].filter((x):x is string=>Boolean(x));if(ids.length===0)return {pageId:null,critical:false,unconfirmed:true};if(ids.some(id=>id!==P1_T04_PAGE_ID))return {pageId:ids[0]??null,critical:true,unconfirmed:false};return {pageId:P1_T04_PAGE_ID,critical:false,unconfirmed:false};}
function validateTarget(post:JsonObject,kind:PostKind){const entry=platformEntry(post);if(!entry)return {ok:false,critical:false,pageUnconfirmed:false,accountId:null,pageId:null};const accountId=postAccountId(entry),explicitPageId=postPageId(entry);if(accountId&&accountId!==P1_T04_ACCOUNT_ID)return {ok:false,critical:true,pageUnconfirmed:false,accountId,pageId:explicitPageId};if(accountId!==P1_T04_ACCOUNT_ID)return {ok:false,critical:false,pageUnconfirmed:false,accountId,pageId:explicitPageId};if(explicitPageId){if(explicitPageId!==P1_T04_PAGE_ID)return {ok:false,critical:true,pageUnconfirmed:false,accountId,pageId:explicitPageId};return {ok:true,critical:false,pageUnconfirmed:false,accountId,pageId:explicitPageId};}if(kind!=='immediate')return {ok:false,critical:false,pageUnconfirmed:true,accountId,pageId:null};if(postState(post)!=='published'||platformState(entry)!=='published')return {ok:false,critical:false,pageUnconfirmed:true,accountId,pageId:null};const alternate=alternateImmediatePageAttestation(entry);if(alternate.critical)return {ok:false,critical:true,pageUnconfirmed:false,accountId,pageId:alternate.pageId};if(alternate.unconfirmed)return {ok:false,critical:false,pageUnconfirmed:true,accountId,pageId:null};return {ok:true,critical:false,pageUnconfirmed:false,accountId,pageId:alternate.pageId};}
function formatCairoLocal(date:Date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:TIMEZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);const get=(type:string)=>parts.find(p=>p.type===type)?.value??'';return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}:${get('second')}`;}
function scheduleMatches(returned:string|null,requested:string,now:Date){if(!returned)return false;const d=new Date(returned);if(!Number.isFinite(d.getTime())||d.getTime()<now.getTime()+48*60*60*1000)return false;return formatCairoLocal(d)===requested;}
function emptyPost(kind:PostKind):P1T04PostEvidence{return {kind,postId:null,createStatus:null,createRequestId:null,readStatus:null,readRequestId:null,replayStatus:null,replayRequestId:null,sameLogicalPost:null,duplicate:false,scheduledRequested:null,scheduledReturned:null,platformPostId:null,publicUrl:null,publishedAt:null,cleanupConfirmed:false,cleanupStatus:null,cleanupRequestId:null,cleanupReadStatus:null,cleanupReadRequestId:null};}

async function createPostRequest(context:ProviderSpikeExecutionContext,body:JsonObject,idempotencyKey:string){return context.request({method:'POST',url:'/v1/posts',headers:{'Idempotency-Key':idempotencyKey},body,safeMetadata:{path:'/v1/posts',method:'POST',idempotency_key_present:true,logical_operation:'post-create'}});}
async function createPostSafely(context:ProviderSpikeExecutionContext,body:JsonObject,idempotencyKey:string){let response:ProviderTransportResponse;let replayed=false;try{response=await createPostRequest(context,body,idempotencyKey);}catch(error){if(!isTransient(error))throw error;response=await createPostRequest(context,body,idempotencyKey);replayed=true;}
 const s=status(response);if(s===429)blockProviderSpike('PROVIDER_RATE_LIMITED','Post create was rate limited.');if(s===409)blockProviderSpike('PUBLISH_OUTCOME_UNKNOWN','Post create returned an in-flight/idempotency conflict; no new logical key was generated.');if(s!==null&&s>=500&&!replayed){response=await createPostRequest(context,body,idempotencyKey);replayed=true;}const s2=status(response);if(s2===429)blockProviderSpike('PROVIDER_RATE_LIMITED','Post create replay was rate limited.');if(s2===409)blockProviderSpike('PUBLISH_OUTCOME_UNKNOWN','Post create replay remained in conflict.');if(s2===401||s2===403)blockProviderSpike('PUBLISHING_ACCOUNT_NOT_HEALTHY','Provider rejected publishing authorization.');if(s2!==200&&s2!==201&&s2!==207)blockProviderSpike('PUBLISH_OUTCOME_UNKNOWN',`Post create outcome could not be established safely (${String(response.status)}).`);
 let post=postEnvelope(response.body);if(!post&&!replayed){response=await createPostRequest(context,body,idempotencyKey);replayed=true;post=postEnvelope(response.body);}if(!post)blockProviderSpike('PUBLISH_OUTCOME_UNKNOWN','Post create returned no identifiable post after bounded same-key replay.');return {response,post,replayed};}
function createBody(kind:PostKind,text:string,scheduledFor?:string):JsonObject{const base:JsonObject={content:text,platforms:[{platform:'facebook',accountId:P1_T04_ACCOUNT_ID,platformSpecificData:{pageId:P1_T04_PAGE_ID}}]};if(kind==='scheduled'){base.scheduledFor=scheduledFor!;base.timezone=TIMEZONE;}if(kind==='immediate')base.publishNow=true;return base;}
function validateCreatedPost(kind:PostKind,post:JsonObject,text:string,scheduledRequested:string|null,now:Date){const id=postId(post),target=validateTarget(post,kind),state=postState(post),entry=platformEntry(post),pstate=platformState(entry);if(!id)return {ok:false,critical:false,pageUnconfirmed:false,id:null};if(target.critical)return {ok:false,critical:true,pageUnconfirmed:false,id};if(target.pageUnconfirmed)return {ok:false,critical:false,pageUnconfirmed:true,id};if(!target.ok)return {ok:false,critical:false,pageUnconfirmed:false,id};if(kind==='draft'&&(state!=='draft'||pstate==='published'))return {ok:false,critical:false,pageUnconfirmed:false,id};if(kind==='scheduled'){const returned=typeof post.scheduledFor==='string'?post.scheduledFor:null;if(state!=='scheduled'||!scheduleMatches(returned,scheduledRequested!,now))return {ok:false,critical:false,id};}if(kind==='immediate'&&!((state==='published'&&pstate==='published')||(state==='publishing'&&(pstate==='pending'||pstate==='publishing'))))return {ok:false,critical:false,id};return {ok:true,critical:false,pageUnconfirmed:false,id};}
function readValid(kind:PostKind,post:JsonObject,text:string,scheduledRequested:string|null,now:Date){const base=validateCreatedPost(kind,post,text,scheduledRequested,now);if(!base.ok)return base;if(content(post)!==text)return {ok:false,critical:false,pageUnconfirmed:false,id:base.id};if(kind==='immediate'){const entry=platformEntry(post);if(postState(post)!=='published'||platformState(entry)!=='published')return {ok:false,critical:false,pageUnconfirmed:false,id:base.id};}return base;}

export async function runP1T04(options:P1T04RunOptions={}):Promise<P1T04RunResult>{
 const live=options.live===true,env=options.env??process.env,providerEnvironment=options.providerEnvironment??'authorized-internal-zernio-test-team',counter:Counter={normal:0,cleanup:0,normalMax:options.normalRequestCeiling??P1_T04_NORMAL_REQUEST_CEILING,cleanupMax:options.cleanupRequestAllowance??P1_T04_CLEANUP_REQUEST_ALLOWANCE},steps:P1T04StepEvidence[]=[];let identityMatch=false,key:P1T04KeyMetadata|null=null,target:P1T04TargetEvidence|null=null,draft:P1T04PostEvidence|null=null,scheduled:P1T04PostEvidence|null=null,immediate:P1T04PostEvidence|null=null,keyCleanup:P1T04KeyCleanup|null=null,wrongTargetObserved=false,pageTargetUnconfirmed=false,duplicateConfirmedPublishObserved=false,cleanupFailureCategory:string|null=null,preflightResult:ProviderSpikeRunResult|null=null;const artifacts:ArtifactState={draftId:null,scheduledId:null,publicId:null};const internalKeyBox:{value:CreatedKeyInternal|null}={value:null};
 const resultBase=()=>({liveEnabled:live,identityMatch,preflight:preflightResult,key,target,draft,scheduled,immediate,keyCleanup,wrongTargetObserved,duplicateConfirmedPublishObserved,normalRequestCount:counter.normal,cleanupRequestCount:counter.cleanup,liveRequestCount:counter.normal+counter.cleanup,steps});const done=(result:Result,errorCategory:string|null):P1T04RunResult=>({...resultBase(),result,errorCategory});if(!live)return done('BLOCKED','LIVE_OPT_IN_REQUIRED');
 if(env.ZERNIO_P1_T04_EXPECTED_FACEBOOK_ACCOUNT_ID!==P1_T04_ACCOUNT_ID)return done('BLOCKED','EXPECTED_PUBLISHING_ACCOUNT_NOT_FOUND');if(env.ZERNIO_P1_T04_EXPECTED_FACEBOOK_PAGE_ID!==P1_T04_PAGE_ID)return done('BLOCKED','EXPECTED_FACEBOOK_PAGE_NOT_FOUND');if(env.ZERNIO_P1_T04_ALLOW_PUBLIC_TEST!=='true')return done('BLOCKED','PUBLIC_TEST_NOT_AUTHORIZED');
 const controlRaw=options.controlTransport??(env.ZERNIO_API_KEY?createZernioLiveTransport(env.ZERNIO_API_KEY):undefined);if(!controlRaw){const preflight=await runProviderSpikeCase(createP1T02TeamPreflightCase('live',env.ZERNIO_EXPECTED_USER_EMAIL,providerEnvironment),{env});steps.push(step(preflight));preflightResult=preflight;return done('BLOCKED',preflight.evidence.error_category);}const control=bounded(controlRaw,counter);const preflight=await runProviderSpikeCase(createP1T02TeamPreflightCase('live',env.ZERNIO_EXPECTED_USER_EMAIL,providerEnvironment,value=>{identityMatch=value.expectedIdentityMatch;}),{env,transport:control,redactionSecrets:redactionSecrets(env)});steps.push(step(preflight));preflightResult=preflight;if(preflight.evidence.result!=='PASS')return done('BLOCKED',preflight.evidence.error_category);
 const runTag=(options.runTag??randomUUID()).replace(/[^a-zA-Z0-9-]/g,'').slice(0,36),syntheticName=`aimm-p1-t04-publishing-${runTag}`,now=options.now??new Date(),sleep=options.sleep??(ms=>new Promise(resolve=>setTimeout(resolve,ms)));
 const keyRun=await runCase('P1-T04-PUBLISHING-KEY-CREATE',3,['ZERNIO_API_KEY'],providerEnvironment,env,control,[],ctx=>createPublishingKey(ctx,syntheticName,k=>{internalKeyBox.value=k;}),o=>obj(o)?.ok===true);steps.push(step(keyRun));const internalKey=internalKeyBox.value as CreatedKeyInternal|null;if(keyRun.evidence.result!=='PASS'||!internalKey)return done(keyRun.evidence.result,keyRun.evidence.error_category);key={...internalKey.metadata,creationStatus:typeof keyRun.evidence.provider_status==='number'?keyRun.evidence.provider_status:null,creationRequestId:keyRun.evidence.provider_request_id};
 const scopedRaw=options.scopedTransportFactory?options.scopedTransportFactory(internalKey.secret):createZernioLiveTransport(internalKey.secret),scoped=bounded(scopedRaw,counter),senv=scopedEnv(internalKey.secret),secrets=[internalKey.secret];
 const revokeKey=async(safety:boolean)=>{if(!internalKey)return true;const ct=safety?bounded(controlRaw,counter,true):control,st=safety?bounded(scopedRaw,counter,true):scoped;const revoke=await runCase('P1-T04-PUBLISHING-KEY-REVOKE',1,['ZERNIO_API_KEY'],providerEnvironment,env,ct,[],async ctx=>{const r=await ctx.request({method:'DELETE',url:`/v1/api-keys/${encodeURIComponent(internalKey!.metadata.providerKeyId)}`,safeMetadata:{path:'/v1/api-keys/{keyId}',method:'DELETE',phase:safety?'cleanup':'normal'}});return {ok:status(r)===200};},o=>obj(o)?.ok===true);steps.push(step(revoke));let valid:boolean|null=null;const verify=await runCase('P1-T04-PUBLISHING-KEY-POST-REVOKE',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,st,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:'/v1/auth/verify',safeMetadata:{path:'/v1/auth/verify',method:'GET',phase:safety?'cleanup':'normal'}});valid=status(r)===200&&obj(r.body)?.valid===true;return {ok:status(r)===401||(status(r)===200&&!valid)};},o=>obj(o)?.ok===true);steps.push(step(verify));keyCleanup={revokeStatus:typeof revoke.evidence.provider_status==='number'?revoke.evidence.provider_status:null,revokeRequestId:revoke.evidence.provider_request_id,revokedKeyValid:valid,verifyStatus:typeof verify.evidence.provider_status==='number'?verify.evidence.provider_status:null,verifyRequestId:verify.evidence.provider_request_id,confirmed:revoke.evidence.result==='PASS'&&verify.evidence.result==='PASS'&&valid===false};return keyCleanup.confirmed;};
 const cleanupOne=async(kind:PostKind,id:string,safety:boolean)=>{const st=safety?bounded(scopedRaw,counter,true):scoped;const evidence=kind==='draft'?draft:kind==='scheduled'?scheduled:immediate;if(!evidence)return false;const rememberFailure=()=>{if(!cleanupFailureCategory)cleanupFailureCategory=kind==='draft'?'DRAFT_TEST_POST_CLEANUP_UNCONFIRMED':kind==='scheduled'?'SCHEDULED_TEST_POST_CLEANUP_UNCONFIRMED':'PUBLISHED_TEST_POST_CLEANUP_UNCONFIRMED';};if(kind==='immediate'){const unpublish=await runCase('P1-T04-PUBLIC-CLEANUP',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,st,secrets,async ctx=>{const r=await ctx.request({method:'POST',url:`/v1/posts/${encodeURIComponent(id)}/unpublish`,body:{platform:'facebook'},safeMetadata:{path:'/v1/posts/{postId}/unpublish',method:'POST',post_id:id,phase:safety?'cleanup':'normal'}});return {ok:status(r)===200};},o=>obj(o)?.ok===true);steps.push(step(unpublish));evidence.cleanupStatus=typeof unpublish.evidence.provider_status==='number'?unpublish.evidence.provider_status:null;evidence.cleanupRequestId=unpublish.evidence.provider_request_id;if(unpublish.evidence.result!=='PASS'){rememberFailure();return false;}const verify=await runCase('P1-T04-PUBLIC-CLEANUP-READBACK',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,st,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:`/v1/posts/${encodeURIComponent(id)}`,safeMetadata:{path:'/v1/posts/{postId}',method:'GET',post_id:id,phase:safety?'cleanup':'normal'}});if(status(r)!==200)return {ok:status(r)===404};const post=postEnvelope(r.body),entry=post?platformEntry(post):null;return {ok:Boolean(post)&&platformState(entry)!=='published'};},o=>obj(o)?.ok===true);steps.push(step(verify));evidence.cleanupReadStatus=typeof verify.evidence.provider_status==='number'?verify.evidence.provider_status:null;evidence.cleanupReadRequestId=verify.evidence.provider_request_id;evidence.cleanupConfirmed=verify.evidence.result==='PASS';if(evidence.cleanupConfirmed)artifacts.publicId=null;else rememberFailure();return evidence.cleanupConfirmed;}
  const del=await runCase(`P1-T04-${kind.toUpperCase()}-CLEANUP`,1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,st,secrets,async ctx=>{const r=await ctx.request({method:'DELETE',url:`/v1/posts/${encodeURIComponent(id)}`,safeMetadata:{path:'/v1/posts/{postId}',method:'DELETE',post_id:id,phase:safety?'cleanup':'normal'}});return {ok:status(r)===200||status(r)===204};},o=>obj(o)?.ok===true);steps.push(step(del));evidence.cleanupStatus=typeof del.evidence.provider_status==='number'?del.evidence.provider_status:null;evidence.cleanupRequestId=del.evidence.provider_request_id;if(del.evidence.result!=='PASS'){rememberFailure();return false;}const verify=await runCase(`P1-T04-${kind.toUpperCase()}-CLEANUP-READBACK`,1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,st,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:`/v1/posts/${encodeURIComponent(id)}`,safeMetadata:{path:'/v1/posts/{postId}',method:'GET',post_id:id,phase:safety?'cleanup':'normal'}});if(status(r)===404)return {ok:true};if(status(r)!==200)return {ok:false};const post=postEnvelope(r.body);return {ok:Boolean(post)&&['cancelled','deleted'].includes(postState(post)??'')};},o=>obj(o)?.ok===true);steps.push(step(verify));evidence.cleanupReadStatus=typeof verify.evidence.provider_status==='number'?verify.evidence.provider_status:null;evidence.cleanupReadRequestId=verify.evidence.provider_request_id;evidence.cleanupConfirmed=verify.evidence.result==='PASS';if(evidence.cleanupConfirmed){if(kind==='draft')artifacts.draftId=null;else artifacts.scheduledId=null;}else rememberFailure();return evidence.cleanupConfirmed;};
 const emergencyCleanup=async()=>{let ok=true;if(artifacts.publicId)ok=(await cleanupOne('immediate',artifacts.publicId,true))&&ok;if(artifacts.scheduledId)ok=(await cleanupOne('scheduled',artifacts.scheduledId,true))&&ok;if(artifacts.draftId)ok=(await cleanupOne('draft',artifacts.draftId,true))&&ok;ok=(await revokeKey(true))&&ok;return ok;};
 const fail=async(result:Result,category:string)=>{const cleanupOk=await emergencyCleanup();if(!cleanupOk){if(cleanupFailureCategory)return done('BLOCKED',cleanupFailureCategory);if(keyCleanup?.confirmed===false)return done('BLOCKED','PUBLISHING_KEY_CLEANUP_UNCONFIRMED');if(category==='PUBLISHED_TEST_POST_CLEANUP_UNCONFIRMED'||category==='SCHEDULED_TEST_POST_CLEANUP_UNCONFIRMED'||category==='DRAFT_TEST_POST_CLEANUP_UNCONFIRMED')return done('BLOCKED',category);return done('BLOCKED','PUBLISHING_ARTIFACT_CLEANUP_UNCONFIRMED');}return done(result,category);};
 const accountOutcomeBox:{value:{accountId:string|null;platform:string|null;profileId:string|null;critical:boolean}|null}={value:null};const accountsRun=await runCase('P1-T04-TARGET-ACCOUNT',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:`/v1/accounts?profileId=${encodeURIComponent(P1_T04_PROFILE_ID)}`,safeMetadata:{path:'/v1/accounts',method:'GET',profile_id:P1_T04_PROFILE_ID}});ensureStatus(r,[200],'Publishing account preflight');const a=targetAccount(r.body);const critical=a.profileId!==P1_T04_PROFILE_ID;accountOutcomeBox.value={accountId:valueId(a.account),platform:a.platform,profileId:a.profileId,critical};return {ok:!critical&&a.platform==='facebook'};},o=>obj(o)?.ok===true);steps.push(step(accountsRun));const accountOutcome=accountOutcomeBox.value as {accountId:string|null;platform:string|null;profileId:string|null;critical:boolean}|null;target={accountId:accountOutcome?.accountId??null,platform:accountOutcome?.platform??null,profileId:accountOutcome?.profileId??null,pageId:null,pageName:null,pageMatch:false,healthStatus:null,canPost:false,accountRequestId:accountsRun.evidence.provider_request_id,pageRequestId:null,healthRequestId:null};if(accountOutcome?.critical){wrongTargetObserved=true;return fail('FAIL','CRITICAL_WRONG_PUBLISHING_TARGET');}if(accountsRun.evidence.result!=='PASS')return fail('BLOCKED',accountsRun.evidence.error_category??'EXPECTED_PUBLISHING_ACCOUNT_NOT_FOUND');
 const pageRun=await runCase('P1-T04-TARGET-PAGE',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:`/v1/accounts/${encodeURIComponent(P1_T04_ACCOUNT_ID)}/facebook-page`,safeMetadata:{path:'/v1/accounts/{accountId}/facebook-page',method:'GET',account_id:P1_T04_ACCOUNT_ID}});ensureStatus(r,[200],'Facebook Page preflight');const parsed=parsePages(r.body),match=parsed.pages.find(p=>valueId(p)===P1_T04_PAGE_ID),selected=typeof parsed.root.selectedPageId==='string'?parsed.root.selectedPageId:null;if(!match||selected&&selected!==P1_T04_PAGE_ID)blockProviderSpike('EXPECTED_FACEBOOK_PAGE_NOT_FOUND','Frozen expected Facebook Page is not the selected/available Page.');target!.pageId=P1_T04_PAGE_ID;target!.pageName=typeof match.name==='string'?match.name:null;target!.pageMatch=true;return {ok:true};},o=>obj(o)?.ok===true);steps.push(step(pageRun));target.pageRequestId=pageRun.evidence.provider_request_id;if(pageRun.evidence.result!=='PASS')return fail('BLOCKED',pageRun.evidence.error_category??'EXPECTED_FACEBOOK_PAGE_NOT_FOUND');
 const healthRun=await runCase('P1-T04-ACCOUNT-HEALTH',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:`/v1/accounts/${encodeURIComponent(P1_T04_ACCOUNT_ID)}/health`,safeMetadata:{path:'/v1/accounts/{accountId}/health',method:'GET',account_id:P1_T04_ACCOUNT_ID}});ensureStatus(r,[200],'Publishing account health');const root=obj(r.body),permissions=obj(root?.permissions),token=obj(root?.tokenStatus),health=typeof root?.status==='string'?root.status:null,canPost=permissions?.canPost===true;target!.healthStatus=health;target!.canPost=canPost;if(valueId(root?.accountId)!==P1_T04_ACCOUNT_ID||root?.platform!=='facebook'||!canPost||token?.valid===false||health==='error'||health==='disconnected')blockProviderSpike('PUBLISHING_ACCOUNT_NOT_HEALTHY','Expected Facebook account is not healthy for posting.');return {ok:true};},o=>obj(o)?.ok===true);steps.push(step(healthRun));target.healthRequestId=healthRun.evidence.provider_request_id;if(healthRun.evidence.result!=='PASS')return fail('BLOCKED',healthRun.evidence.error_category??'PUBLISHING_ACCOUNT_NOT_HEALTHY');
 const contents={draft:`AI Marketing Manager internal provider test — P1-T04 — ${runTag} — temporary draft test post.`,scheduled:`AI Marketing Manager internal provider test — P1-T04 — ${runTag} — temporary scheduled test post.`,immediate:`AI Marketing Manager internal provider test — P1-T04 — ${runTag} — temporary public test post.`};
 const draftKey=randomUUID(),draftBody=createBody('draft',contents.draft);draft=emptyPost('draft');const draftCreateBox:{value:{post:JsonObject;response:ProviderTransportResponse}|null}={value:null};const draftRun=await runCase('P1-T04-DRAFT-CREATE',2,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const c=await createPostSafely(ctx,draftBody,draftKey),v=validateCreatedPost('draft',c.post,contents.draft,null,now);draftCreateBox.value={post:c.post,response:c.response};if(v.id)artifacts.draftId=v.id;if(v.critical)wrongTargetObserved=true;if(v.pageUnconfirmed)pageTargetUnconfirmed=true;return {ok:v.ok,critical:v.critical,pageUnconfirmed:v.pageUnconfirmed};},o=>obj(o)?.ok===true);steps.push(step(draftRun));const draftCreate=draftCreateBox.value as {post:JsonObject;response:ProviderTransportResponse}|null;draft.postId=draftCreate?postId(draftCreate.post):artifacts.draftId;draft.createStatus=typeof draftRun.evidence.provider_status==='number'?draftRun.evidence.provider_status:null;draft.createRequestId=draftRun.evidence.provider_request_id;if(wrongTargetObserved)return fail('FAIL','CRITICAL_WRONG_PUBLISHING_TARGET');if(pageTargetUnconfirmed)return fail('BLOCKED','PUBLISHING_PAGE_TARGET_UNCONFIRMED');if(draftRun.evidence.result!=='PASS')return fail('BLOCKED',draftRun.evidence.error_category??'PUBLISH_OUTCOME_UNKNOWN');
 const draftRead=await runCase('P1-T04-DRAFT-READ',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:`/v1/posts/${encodeURIComponent(artifacts.draftId!)}`,safeMetadata:{path:'/v1/posts/{postId}',method:'GET',post_id:artifacts.draftId}});ensureStatus(r,[200],'Draft read-back');const p=postEnvelope(r.body);if(!p)return {ok:false};const v=readValid('draft',p,contents.draft,null,now);if(v.critical)wrongTargetObserved=true;if(v.pageUnconfirmed)pageTargetUnconfirmed=true;return {ok:v.ok};},o=>obj(o)?.ok===true);steps.push(step(draftRead));draft.readStatus=typeof draftRead.evidence.provider_status==='number'?draftRead.evidence.provider_status:null;draft.readRequestId=draftRead.evidence.provider_request_id;if(wrongTargetObserved)return fail('FAIL','CRITICAL_WRONG_PUBLISHING_TARGET');if(pageTargetUnconfirmed)return fail('BLOCKED','PUBLISHING_PAGE_TARGET_UNCONFIRMED');if(draftRead.evidence.result!=='PASS')return fail('BLOCKED',draftRead.evidence.error_category??'MALFORMED_PROVIDER_RESPONSE');
 let replayPost:JsonObject|null=null;const replayRun=await runCase('P1-T04-DRAFT-IDEMPOTENCY-REPLAY',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const r=await createPostRequest(ctx,draftBody,draftKey);ensureStatus(r,[200,201],'Draft idempotency replay');const p=postEnvelope(r.body);replayPost=p;const targetCheck=p?validateTarget(p,'draft'):{ok:false,critical:false,pageUnconfirmed:false};if(targetCheck.critical)wrongTargetObserved=true;if(targetCheck.pageUnconfirmed)pageTargetUnconfirmed=true;const id=postId(p);if(id&&id!==artifacts.draftId){duplicateConfirmedPublishObserved=true;return {ok:false};}return {ok:id===artifacts.draftId};},o=>obj(o)?.ok===true);steps.push(step(replayRun));draft.replayStatus=typeof replayRun.evidence.provider_status==='number'?replayRun.evidence.provider_status:null;draft.replayRequestId=replayRun.evidence.provider_request_id;draft.sameLogicalPost=Boolean(replayPost&&postId(replayPost)===artifacts.draftId);draft.duplicate=duplicateConfirmedPublishObserved;if(wrongTargetObserved)return fail('FAIL','CRITICAL_WRONG_PUBLISHING_TARGET');if(pageTargetUnconfirmed)return fail('BLOCKED','PUBLISHING_PAGE_TARGET_UNCONFIRMED');if(duplicateConfirmedPublishObserved){const extra=postId(replayPost);if(extra&&extra!==artifacts.draftId){const temp=artifacts.draftId;artifacts.draftId=extra;await cleanupOne('draft',extra,true);artifacts.draftId=temp;}return fail('FAIL','CRITICAL_DUPLICATE_CONFIRMED_PUBLISH');}if(replayRun.evidence.result!=='PASS')return fail('BLOCKED',replayRun.evidence.error_category??'PUBLISH_OUTCOME_UNKNOWN');if(!await cleanupOne('draft',artifacts.draftId!,false))return fail('BLOCKED','DRAFT_TEST_POST_CLEANUP_UNCONFIRMED');
 const future=new Date(now.getTime()+72*60*60*1000),requestedSchedule=formatCairoLocal(future),scheduledKey=randomUUID(),scheduledBody=createBody('scheduled',contents.scheduled,requestedSchedule);scheduled=emptyPost('scheduled');scheduled.scheduledRequested=requestedSchedule;const scheduledPostBox:{value:JsonObject|null}={value:null};const scheduledRun=await runCase('P1-T04-SCHEDULED-CREATE',2,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const c=await createPostSafely(ctx,scheduledBody,scheduledKey);scheduledPostBox.value=c.post;const v=validateCreatedPost('scheduled',c.post,contents.scheduled,requestedSchedule,now);if(v.id)artifacts.scheduledId=v.id;if(v.critical)wrongTargetObserved=true;if(v.pageUnconfirmed)pageTargetUnconfirmed=true;return {ok:v.ok};},o=>obj(o)?.ok===true);steps.push(step(scheduledRun));const scheduledPost=scheduledPostBox.value as JsonObject|null;scheduled.postId=scheduledPost?postId(scheduledPost):artifacts.scheduledId;scheduled.createStatus=typeof scheduledRun.evidence.provider_status==='number'?scheduledRun.evidence.provider_status:null;scheduled.createRequestId=scheduledRun.evidence.provider_request_id;scheduled.scheduledReturned=typeof scheduledPost?.scheduledFor==='string'?scheduledPost.scheduledFor:null;if(wrongTargetObserved)return fail('FAIL','CRITICAL_WRONG_PUBLISHING_TARGET');if(pageTargetUnconfirmed)return fail('BLOCKED','PUBLISHING_PAGE_TARGET_UNCONFIRMED');if(scheduledRun.evidence.result!=='PASS')return fail('BLOCKED',scheduledRun.evidence.error_category??'PUBLISH_OUTCOME_UNKNOWN');
 const scheduledRead=await runCase('P1-T04-SCHEDULED-READ',1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:`/v1/posts/${encodeURIComponent(artifacts.scheduledId!)}`,safeMetadata:{path:'/v1/posts/{postId}',method:'GET',post_id:artifacts.scheduledId}});ensureStatus(r,[200],'Scheduled read-back');const p=postEnvelope(r.body);if(!p)return {ok:false};const v=readValid('scheduled',p,contents.scheduled,requestedSchedule,now);if(v.critical)wrongTargetObserved=true;if(v.pageUnconfirmed)pageTargetUnconfirmed=true;scheduled!.scheduledReturned=typeof p.scheduledFor==='string'?p.scheduledFor:null;return {ok:v.ok};},o=>obj(o)?.ok===true);steps.push(step(scheduledRead));scheduled.readStatus=typeof scheduledRead.evidence.provider_status==='number'?scheduledRead.evidence.provider_status:null;scheduled.readRequestId=scheduledRead.evidence.provider_request_id;if(wrongTargetObserved)return fail('FAIL','CRITICAL_WRONG_PUBLISHING_TARGET');if(pageTargetUnconfirmed)return fail('BLOCKED','PUBLISHING_PAGE_TARGET_UNCONFIRMED');if(scheduledRead.evidence.result!=='PASS')return fail('BLOCKED',scheduledRead.evidence.error_category??'MALFORMED_PROVIDER_RESPONSE');if(!await cleanupOne('scheduled',artifacts.scheduledId!,false))return fail('BLOCKED','SCHEDULED_TEST_POST_CLEANUP_UNCONFIRMED');
 const immediateKey=randomUUID(),immediateBody=createBody('immediate',contents.immediate);immediate=emptyPost('immediate');const immediatePostBox:{value:JsonObject|null}={value:null};const immediateRun=await runCase('P1-T04-IMMEDIATE-CREATE',2,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const c=await createPostSafely(ctx,immediateBody,immediateKey);immediatePostBox.value=c.post;const v=validateCreatedPost('immediate',c.post,contents.immediate,null,now);if(v.id)artifacts.publicId=v.id;if(v.critical)wrongTargetObserved=true;if(v.pageUnconfirmed)pageTargetUnconfirmed=true;return {ok:v.ok};},o=>obj(o)?.ok===true);steps.push(step(immediateRun));const immediatePost=immediatePostBox.value as JsonObject|null;immediate.postId=immediatePost?postId(immediatePost):artifacts.publicId;immediate.createStatus=typeof immediateRun.evidence.provider_status==='number'?immediateRun.evidence.provider_status:null;immediate.createRequestId=immediateRun.evidence.provider_request_id;if(wrongTargetObserved)return fail('FAIL','CRITICAL_WRONG_PUBLISHING_TARGET');if(pageTargetUnconfirmed)return fail('BLOCKED','PUBLISHING_PAGE_TARGET_UNCONFIRMED');if(immediateRun.evidence.result!=='PASS')return fail('BLOCKED',immediateRun.evidence.error_category??'PUBLISH_OUTCOME_UNKNOWN');
 const readImmediate=async(testId:string)=>runCase(testId,1,['P1_T04_SCOPED_KEY_RUNTIME'],providerEnvironment,senv,scoped,secrets,async ctx=>{const r=await ctx.request({method:'GET',url:`/v1/posts/${encodeURIComponent(artifacts.publicId!)}`,safeMetadata:{path:'/v1/posts/{postId}',method:'GET',post_id:artifacts.publicId}});ensureStatus(r,[200],'Published post read-back');const p=postEnvelope(r.body);if(!p)return {ok:false,published:false};const v=readValid('immediate',p,contents.immediate,null,now);if(v.critical)wrongTargetObserved=true;if(v.pageUnconfirmed)pageTargetUnconfirmed=true;const e=platformEntry(p);immediate!.platformPostId=typeof e?.platformPostId==='string'?e.platformPostId:null;immediate!.publicUrl=typeof e?.platformPostUrl==='string'?e.platformPostUrl:null;immediate!.publishedAt=typeof e?.publishedAt==='string'?e.publishedAt:typeof p.publishedAt==='string'?p.publishedAt:null;return {ok:v.ok,published:v.ok};},o=>obj(o)?.ok===true);
 let immediateRead=await readImmediate('P1-T04-IMMEDIATE-READ');steps.push(step(immediateRead));if(immediateRead.evidence.result!=='PASS'&&!wrongTargetObserved&&postState(immediatePost)==='publishing'){await sleep(1500);immediateRead=await readImmediate('P1-T04-IMMEDIATE-READ-BOUNDED-RETRY');steps.push(step(immediateRead));}immediate.readStatus=typeof immediateRead.evidence.provider_status==='number'?immediateRead.evidence.provider_status:null;immediate.readRequestId=immediateRead.evidence.provider_request_id;if(wrongTargetObserved)return fail('FAIL','CRITICAL_WRONG_PUBLISHING_TARGET');if(pageTargetUnconfirmed)return fail('BLOCKED','PUBLISHING_PAGE_TARGET_UNCONFIRMED');if(immediateRead.evidence.result!=='PASS')return fail('BLOCKED',immediateRead.evidence.error_category??'PUBLISH_OUTCOME_UNKNOWN');if(!await cleanupOne('immediate',artifacts.publicId!,false))return fail('BLOCKED','PUBLISHED_TEST_POST_CLEANUP_UNCONFIRMED');if(!await revokeKey(false))return done('BLOCKED','PUBLISHING_KEY_CLEANUP_UNCONFIRMED');
 return done('PASS',null);
}
