import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';

type JsonObject=Record<string,unknown>;
const F02_READINESS_HEADER='x-aimm-p1-t05-readiness';
const F02_READINESS_CONFIRM_HEADER='x-aimm-p1-t05-readiness-confirmed';
const F02_RECEIVER_HEADER='x-aimm-p1-t05-receiver';

export interface P1T05DeliveryEvidence{event:string|null;eventId:string|null;payloadId:string|null;profileId:string|null;profileAttributionSource:string|null;timestamp:string|null;signatureValid:boolean;headerBodyIdMatch:boolean;headerEventMatch:boolean;duplicate:boolean;responseStatus:number;ackLatencyMs:number;rawBodySha256:string;receivedAt:string;}
export interface P1T05ReceiverSnapshot{deliveries:P1T05DeliveryEvidence[];testDeliveries:number;realDeliveries:number;logicalUniqueRealEvents:number;foreignProfileObserved:boolean;profileAttributionUnconfirmed:boolean;readinessHits?:number;readinessConfirmedHits?:number;}
export interface P1T05ReceiverController{port:number;localUrl:string;receiverPath?:string;readinessMarker?:string;snapshot():P1T05ReceiverSnapshot;waitForTest(timeoutMs:number):Promise<P1T05DeliveryEvidence|null>;waitForReal(count:number,timeoutMs:number):Promise<P1T05DeliveryEvidence[]>;waitForReadiness?(count:number,timeoutMs:number):Promise<boolean>;close():Promise<void>;}
export interface P1T05VerifyOptions{secret:string;expectedProfileId:string;expectedAccountId:string;expectedContentMarker?:string;seen?:Set<string>;failedOnce?:Set<string>;now?:()=>number;onParse?:()=>void;}
export interface P1T05VerifyResult{status:number;evidence:P1T05DeliveryEvidence;payload:JsonObject|null;acceptedForDedupe:boolean;}
export interface P1T05VpsReadinessEvidence{ready:boolean;hostname:string;path:string;httpStatus:number|null;tlsSuccess:boolean;receiverMarkerMatch:boolean;receiverConfirmed:boolean;redirected:boolean;latencyMs:number;timestamp:string;errorCategory:string|null;}

function obj(v:unknown):JsonObject|null{return typeof v==='object'&&v!==null&&!Array.isArray(v)?v as JsonObject:null;}
function text(v:unknown){return typeof v==='string'&&v?v:null;}
function header(headers:Record<string,string|string[]|undefined>,name:string){const v=headers[name.toLowerCase()];return Array.isArray(v)?v[0]??null:typeof v==='string'?v:null;}
function safeEqualHex(expected:string,provided:string|null){if(!provided||!/^[0-9a-f]{64}$/.test(provided)||expected.length!==provided.length)return false;const a=Buffer.from(expected,'hex'),b=Buffer.from(provided,'hex');return a.length===b.length&&timingSafeEqual(a,b);}
function profileAttribution(payload:JsonObject,expectedAccountId:string,expectedProfileId:string):{profileId:string|null;source:string|null}{
 const direct=text(payload.profileId);if(direct)return {profileId:direct,source:'payload.profileId'};
 const account=obj(payload.account);const aid=text(account?.profileId);if(aid)return {profileId:aid,source:'payload.account.profileId'};const topAccountId=text(account?.accountId)??text(account?.id)??text(account?._id);if(topAccountId===expectedAccountId)return {profileId:expectedProfileId,source:'payload.account.accountId+frozen-preflight'};
 const post=obj(payload.post);const postAccount=obj(post?.account);const paid=text(postAccount?.profileId);if(paid)return {profileId:paid,source:'payload.post.account.profileId'};const postAccountId=text(post?.accountId)??text(postAccount?.accountId)??text(postAccount?.id)??text(postAccount?._id);if(postAccountId===expectedAccountId)return {profileId:expectedProfileId,source:'payload.post.accountId+frozen-preflight'};
 if(Array.isArray(post?.platforms)){for(const raw of post.platforms){const p=obj(raw),a=obj(p?.account),pid=text(p?.profileId)??text(a?.profileId);if(pid)return {profileId:pid,source:'payload.post.platforms.profileId'};const accountId=text(p?.accountId)??text(a?._id)??text(a?.id);if(accountId===expectedAccountId)return {profileId:expectedProfileId,source:'payload.post.platforms.accountId+frozen-preflight'};}}
 return {profileId:null,source:null};
}
function markerMatches(payload:JsonObject,marker?:string){if(!marker)return true;const post=obj(payload.post);return typeof post?.content==='string'&&post.content.includes(marker);}
function safeReceiverPath(path:string|undefined){const value=path??'/zernio';if(!value.startsWith('/')||value.includes('?')||value.includes('#')||value.includes('..'))throw new Error('INVALID_P1_T05_RECEIVER_PATH');return value;}

export function verifyP1T05Delivery(rawBody:Buffer,headers:Record<string,string|string[]|undefined>,options:P1T05VerifyOptions):P1T05VerifyResult{
 const start=options.now?.()??Date.now(),signature=header(headers,'x-zernio-signature'),computed=createHmac('sha256',options.secret).update(rawBody).digest('hex'),signatureValid=safeEqualHex(computed,signature),base:P1T05DeliveryEvidence={event:null,eventId:header(headers,'x-zernio-event-id'),payloadId:null,profileId:null,profileAttributionSource:null,timestamp:null,signatureValid,headerBodyIdMatch:false,headerEventMatch:false,duplicate:false,responseStatus:400,ackLatencyMs:0,rawBodySha256:createHash('sha256').update(rawBody).digest('hex'),receivedAt:new Date().toISOString()};
 if(!signatureValid){base.responseStatus=signature?400:401;base.ackLatencyMs=Math.max(0,(options.now?.()??Date.now())-start);return {status:base.responseStatus,evidence:base,payload:null,acceptedForDedupe:false};}
 let payload:JsonObject|null=null;try{options.onParse?.();payload=obj(JSON.parse(rawBody.toString('utf8')));}catch{payload=null;}if(!payload){base.responseStatus=400;base.ackLatencyMs=Math.max(0,(options.now?.()??Date.now())-start);return {status:400,evidence:base,payload:null,acceptedForDedupe:false};}
 const event=text(payload.event),payloadId=text(payload.id),eventId=base.eventId,eventHeader=header(headers,'x-zernio-event'),headerBodyIdMatch=Boolean(payloadId&&eventId&&payloadId===eventId),headerEventMatch=Boolean(event&&eventHeader&&event===eventHeader);base.event=event;base.payloadId=payloadId;base.headerBodyIdMatch=headerBodyIdMatch;base.headerEventMatch=headerEventMatch;base.timestamp=text(payload.timestamp);
 if(!headerBodyIdMatch||!headerEventMatch){base.responseStatus=400;base.ackLatencyMs=Math.max(0,(options.now?.()??Date.now())-start);return {status:400,evidence:base,payload,acceptedForDedupe:false};}
 if(event==='webhook.test'){base.responseStatus=204;base.ackLatencyMs=Math.max(0,(options.now?.()??Date.now())-start);return {status:204,evidence:base,payload,acceptedForDedupe:true};}
 if(event!=='post.scheduled'||!markerMatches(payload,options.expectedContentMarker)){base.responseStatus=204;base.ackLatencyMs=Math.max(0,(options.now?.()??Date.now())-start);return {status:204,evidence:base,payload,acceptedForDedupe:false};}
 const attribution=profileAttribution(payload,options.expectedAccountId,options.expectedProfileId);base.profileId=attribution.profileId;base.profileAttributionSource=attribution.source;if(attribution.profileId&&attribution.profileId!==options.expectedProfileId){base.responseStatus=409;base.ackLatencyMs=Math.max(0,(options.now?.()??Date.now())-start);return {status:409,evidence:base,payload,acceptedForDedupe:false};}if(!attribution.profileId){base.responseStatus=422;base.ackLatencyMs=Math.max(0,(options.now?.()??Date.now())-start);return {status:422,evidence:base,payload,acceptedForDedupe:false};}
 const seen=options.seen??new Set<string>(),failed=options.failedOnce??new Set<string>(),duplicate=seen.has(payloadId!);base.duplicate=duplicate;seen.add(payloadId!);if(!failed.has(payloadId!)){failed.add(payloadId!);base.responseStatus=500;}else base.responseStatus=204;base.ackLatencyMs=Math.max(0,(options.now?.()??Date.now())-start);return {status:base.responseStatus,evidence:base,payload,acceptedForDedupe:true};
}

export async function startP1T05Receiver(options:{secret:string;expectedProfileId:string;expectedAccountId:string;expectedContentMarker:string;host?:string;port?:number;path?:string;readinessMarker?:string}):Promise<P1T05ReceiverController>{
 const seen=new Set<string>(),failedOnce=new Set<string>(),deliveries:P1T05DeliveryEvidence[]=[];const waiters=new Set<()=>void>();let readinessHits=0,readinessConfirmedHits=0;const receiverPath=safeReceiverPath(options.path),readinessMarker=options.readinessMarker??'p1-t05-provider-spike';const notify=()=>{for(const w of [...waiters])w();};
 const server=createServer(async(req:IncomingMessage,res:ServerResponse)=>{if(req.method!=='POST'||req.url!==receiverPath){res.statusCode=404;res.end();return;}const readiness=header(req.headers,F02_READINESS_HEADER),confirmation=header(req.headers,F02_READINESS_CONFIRM_HEADER);if(readiness===readinessMarker||confirmation===readinessMarker){if(readiness===readinessMarker)readinessHits++;if(confirmation===readinessMarker)readinessConfirmedHits++;res.setHeader(F02_RECEIVER_HEADER,readinessMarker);res.statusCode=401;notify();res.end();return;}const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk));const raw=Buffer.concat(chunks),headers:Record<string,string|string[]|undefined>={};for(const [k,v]of Object.entries(req.headers))headers[k]=v;const result=verifyP1T05Delivery(raw,headers,{...options,seen,failedOnce});deliveries.push(result.evidence);notify();res.statusCode=result.status;res.end();});
 await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(options.port??0,options.host??'127.0.0.1',()=>resolve());});const address=server.address();if(!address||typeof address==='string')throw new Error('Receiver did not bind TCP port.');
 const snapshot=():P1T05ReceiverSnapshot=>{const real=deliveries.filter(x=>x.event==='post.scheduled'&&x.signatureValid),ids=new Set(real.map(x=>x.eventId).filter((x):x is string=>Boolean(x)));return {deliveries:deliveries.map(x=>({...x})),testDeliveries:deliveries.filter(x=>x.event==='webhook.test'&&x.signatureValid).length,realDeliveries:real.length,logicalUniqueRealEvents:ids.size,foreignProfileObserved:real.some(x=>Boolean(x.profileId)&&x.profileId!==options.expectedProfileId),profileAttributionUnconfirmed:real.some(x=>!x.profileId),readinessHits,readinessConfirmedHits};};
 const wait=async(predicate:()=>boolean,timeoutMs:number)=>{if(predicate())return true;return new Promise<boolean>(resolve=>{const timer=setTimeout(()=>{waiters.delete(done);resolve(false);},timeoutMs);const done=()=>{if(predicate()){clearTimeout(timer);waiters.delete(done);resolve(true);}else waiters.add(done);};waiters.add(done);});};
 return {port:address.port,localUrl:`http://${options.host??'127.0.0.1'}:${address.port}${receiverPath}`,receiverPath,readinessMarker,snapshot,waitForTest:async ms=>{await wait(()=>snapshot().testDeliveries>=1,ms);return snapshot().deliveries.find(x=>x.event==='webhook.test')??null;},waitForReal:async(count,ms)=>{await wait(()=>snapshot().realDeliveries>=count,ms);return snapshot().deliveries.filter(x=>x.event==='post.scheduled'&&x.signatureValid);},waitForReadiness:(count,ms)=>wait(()=>(snapshot().readinessConfirmedHits??0)>=count,ms),close:()=>new Promise<void>(resolve=>server.close(()=>resolve()))};
}

export async function probeP1T05ReceiverHttps(url:string,options:{attempts?:number;sleep?:(ms:number)=>Promise<void>;fetcher?:typeof fetch}={}):Promise<boolean>{
 const attempts=options.attempts??15,sleep=options.sleep??(ms=>new Promise(r=>setTimeout(r,ms))),fetcher=options.fetcher??fetch;
 for(let i=0;i<attempts;i++){try{const response=await fetcher(url,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});if(response.status===401)return true;}catch{}if(i+1<attempts)await sleep(1000);}
 return false;
}

export async function runAfterP1T05ReceiverReadiness<T>(url:string,onReady:()=>Promise<T>,options:{attempts?:number;sleep?:(ms:number)=>Promise<void>;fetcher?:typeof fetch}={}):Promise<{ready:boolean;value:T|null}>{
 if(!await probeP1T05ReceiverHttps(url,options))return {ready:false,value:null};
 return {ready:true,value:await onReady()};
}

export async function probeP1T05VpsReceiverHttps(url:string,readinessMarker:string,options:{fetcher?:typeof fetch;timeoutMs?:number;now?:()=>number}={}):Promise<P1T05VpsReadinessEvidence>{
 const timestamp=new Date().toISOString(),started=options.now?.()??Date.now();let parsed:URL;try{parsed=new URL(url);}catch{return{ready:false,hostname:'',path:'',httpStatus:null,tlsSuccess:false,receiverMarkerMatch:false,receiverConfirmed:false,redirected:false,latencyMs:0,timestamp,errorCategory:'INVALID_VPS_RECEIVER_URL'};}
 const base={hostname:parsed.hostname,path:parsed.pathname,httpStatus:null as number|null,tlsSuccess:false,receiverMarkerMatch:false,receiverConfirmed:false,redirected:false,latencyMs:0,timestamp,errorCategory:null as string|null};
 if(parsed.protocol!=='https:'||parsed.username||parsed.password||parsed.search||parsed.hash)return{ready:false,...base,errorCategory:'INVALID_VPS_RECEIVER_URL'};
 const fetcher=options.fetcher??fetch,request=async(headerName:string)=>fetcher(url,{method:'POST',redirect:'manual',headers:{'content-type':'application/json',[headerName]:readinessMarker},body:'{}',signal:AbortSignal.timeout(options.timeoutMs??5000)});
 try{const response=await request(F02_READINESS_HEADER),latencyMs=Math.max(0,(options.now?.()??Date.now())-started),redirected=response.status>=300&&response.status<400,receiverMarkerMatch=response.headers.get(F02_RECEIVER_HEADER)===readinessMarker;if(redirected)return{ready:false,...base,httpStatus:response.status,tlsSuccess:true,receiverMarkerMatch,redirected:true,latencyMs,errorCategory:'VPS_READINESS_REDIRECTED'};if(response.status!==401)return{ready:false,...base,httpStatus:response.status,tlsSuccess:true,receiverMarkerMatch,latencyMs,errorCategory:'VPS_READINESS_STATUS_UNEXPECTED'};if(!receiverMarkerMatch)return{ready:false,...base,httpStatus:response.status,tlsSuccess:true,receiverMarkerMatch:false,latencyMs,errorCategory:'VPS_READINESS_WRONG_HANDLER'};const confirmation=await request(F02_READINESS_CONFIRM_HEADER),confirmed=confirmation.status===401&&confirmation.headers.get(F02_RECEIVER_HEADER)===readinessMarker;return{ready:confirmed,...base,httpStatus:response.status,tlsSuccess:true,receiverMarkerMatch:true,receiverConfirmed:confirmed,latencyMs:Math.max(0,(options.now?.()??Date.now())-started),errorCategory:confirmed?null:'VPS_READINESS_CONFIRMATION_FAILED'};}catch{return{ready:false,...base,latencyMs:Math.max(0,(options.now?.()??Date.now())-started),errorCategory:'VPS_READINESS_TLS_OR_NETWORK_FAILURE'};}
}

export async function runAfterP1T05ExternalReceiverReadiness<T>(receiver:P1T05ReceiverController,onReady:()=>Promise<T>,options:{timeoutMs?:number;baselineHits?:number}={}):Promise<{ready:boolean;value:T|null;readinessHits:number}>{
 const baseline=options.baselineHits??(receiver.snapshot().readinessConfirmedHits??0);if(!receiver.waitForReadiness)return{ready:false,value:null,readinessHits:baseline};const ready=await receiver.waitForReadiness(baseline+1,options.timeoutMs??60000),hits=receiver.snapshot().readinessConfirmedHits??baseline;if(!ready||hits<=baseline)return{ready:false,value:null,readinessHits:hits};return{ready:true,value:await onReady(),readinessHits:hits};
}
