import { randomUUID } from 'node:crypto';
import { blockProviderSpike, runProviderSpikeCase } from './harness.js';
import { createP1T02TeamPreflightCase, createZernioLiveTransport, P1_T02_PROFILE_A, P1_T02_PROFILE_A_RECORDED_ID, P1_T02_PROFILE_B, P1_T02_PROFILE_B_RECORDED_ID } from './p1-t02-zernio.js';
import type { ProviderSpikeExecutionContext, ProviderSpikeRunResult, ProviderSpikeTestCase, ProviderTransport, ProviderTransportResponse } from './types.js';

const SAFE_HEADERS=['content-type','retry-after','x-request-id','x-correlation-id','x-ratelimit-limit','x-ratelimit-remaining','x-ratelimit-reset'] as const;
const LIVE_REQUEST_CEILING=16;
const EXPIRY_DAYS=1;
type JsonObject=Record<string,unknown>;
type LogicalKey='A'|'B';
interface KeySpec{logicalKey:LogicalKey;profileId:string;profileName:string;}
const KEY_A:KeySpec={logicalKey:'A',profileId:P1_T02_PROFILE_A_RECORDED_ID,profileName:P1_T02_PROFILE_A.name};
const KEY_B:KeySpec={logicalKey:'B',profileId:P1_T02_PROFILE_B_RECORDED_ID,profileName:P1_T02_PROFILE_B.name};

export interface P1T03KeyMetadata{logicalKey:LogicalKey;providerKeyId:string;syntheticName:string;scope:'profiles';permittedProfileId:string;permission:'read';expiresAt:string;creationStatus:number|null;creationRequestId:string|null;creationLatencyMs:number;}
interface P1T03CreatedKeyInternal{metadata:P1T03KeyMetadata;secret:string;}
export interface P1T03ProbeRecord{endpoint:string;status:number|null;requestId:string|null;visibleProfileCount:number;ownProfileVisible:boolean;foreignProfileVisible:boolean;}
export interface P1T03IsolationOutcome{logicalKey:LogicalKey;fullVisibleProfileCount:number;ownProfileVisible:boolean;foreignProfileVisible:boolean;ownExactMatch:boolean;crossLookupIsolated:boolean;criticalLeakage:boolean;probes:P1T03ProbeRecord[];}
export interface P1T03CleanupOutcome{logicalKey:LogicalKey;providerKeyId:string;revokeResult:'PASS'|'FAIL'|'BLOCKED';revokeStatus:number|string|null;revokeRequestId:string|null;postRevokeCredentialValid:boolean|null;verifyStatus:number|string|null;verifyRequestId:string|null;confirmed:boolean;}
export interface P1T03RunResult{liveEnabled:boolean;result:'PASS'|'FAIL'|'BLOCKED';errorCategory:string|null;preflight:ProviderSpikeRunResult|null;identityMatch:boolean;keyA:P1T03KeyMetadata|null;keyB:P1T03KeyMetadata|null;isolationA:P1T03IsolationOutcome|null;isolationB:P1T03IsolationOutcome|null;cleanup:P1T03CleanupOutcome[];crossProfileLeakageObserved:boolean;liveRequestCount:number;}
export interface P1T03RunOptions{live?:boolean;env?:NodeJS.ProcessEnv;providerEnvironment?:string;controlTransport?:ProviderTransport;scopedTransportFactory?:(secret:string)=>ProviderTransport;requestCeiling?:number;runTag?:string;}

function obj(value:unknown):JsonObject|null{return typeof value==='object'&&value!==null&&!Array.isArray(value)?value as JsonObject:null;}
function status(response:ProviderTransportResponse){return typeof response.status==='number'?response.status:null;}
function header(response:ProviderTransportResponse,name:string){const target=name.toLowerCase();for(const [key,value] of Object.entries(response.headers??{}))if(key.toLowerCase()===target&&value)return value;return undefined;}
function requestId(response:ProviderTransportResponse){return header(response,'x-request-id')??header(response,'x-correlation-id')??null;}
function errorCategory(error:unknown){return obj(error)?.category as string|undefined;}
function profileId(value:JsonObject){const id=value._id??value.id;return typeof id==='string'&&id? id:null;}
function profileName(value:JsonObject){return typeof value.name==='string'?value.name:null;}
function parseProfiles(body:unknown){const root=obj(body);if(!root||!Array.isArray(root.profiles))blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Profile response is missing profiles array.');return root.profiles.map(obj).filter((x):x is JsonObject=>Boolean(x));}
function parseApiKeys(body:unknown){const root=obj(body);if(!root||!Array.isArray(root.apiKeys))blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','API key list response is missing apiKeys array.');return root.apiKeys.map(obj).filter((x):x is JsonObject=>Boolean(x));}
function normalizedProfileIds(value:unknown){if(!Array.isArray(value))return null;const ids:string[]=[];for(const item of value){if(typeof item==='string'&&item){ids.push(item);continue;}const o=obj(item);const id=o?profileId(o):null;if(!id)return null;ids.push(id);}return ids;}
function commonCase(testId:string,maxRequests:number,requiredCredentialEnvVars:readonly string[],providerEnvironment:string):ProviderSpikeTestCase{return {testId,provider:'Zernio',capability:'Scoped Keys',providerEnvironment,mode:'live',timeoutMs:5000,maxRequests,requiredCredentialEnvVars,liveSafety:{enabled:true},safeResponseHeaders:SAFE_HEADERS,requestIdExtractor:r=>requestId(r)??undefined,execute:async()=>({ok:true}),assert:async()=>true};}
function blockTransient(response:ProviderTransportResponse,operation:string){const s=status(response);if(s===429)blockProviderSpike('HTTP_429',`${operation} was rate limited.`);if(s!==null&&s>=500)blockProviderSpike('PROVIDER_5XX_BLOCKED',`${operation} returned provider 5xx.`);}
function blockControlStatus(response:ProviderTransportResponse,operation:string,expected:number){const s=status(response);if(s===401||s===403)blockProviderSpike('PROVIDER_AUTHORIZATION_BLOCKED',`${operation} was not authorized.`);blockTransient(response,operation);if(s!==expected)blockProviderSpike('PROVIDER_HTTP_BLOCKED',`${operation} returned unexpected status ${String(response.status)}.`);}
function redactionSecrets(env:NodeJS.ProcessEnv){return env.ZERNIO_EXPECTED_USER_EMAIL?[env.ZERNIO_EXPECTED_USER_EMAIL]:[];}
function runtimeScopedEnv(secret:string):NodeJS.ProcessEnv{return {P1_T03_SCOPED_KEY_RUNTIME:secret};}

function aggregateBounded(transport:ProviderTransport,counter:{count:number;max:number}):ProviderTransport{return {kind:transport.kind,send:async(request,context)=>{if(counter.count>=counter.max)blockProviderSpike('REQUEST_LIMIT_EXCEEDED',`P1-T03 aggregate request ceiling of ${counter.max} reached.`);counter.count++;return transport.send(request,context);}};}

async function reconcileUnknownCreate(context:ProviderSpikeExecutionContext,syntheticName:string){
 const list=await context.request({method:'GET',url:'/v1/api-keys',safeMetadata:{path:'/v1/api-keys',method:'GET',purpose:'unknown-create-exact-name-reconciliation',synthetic_name:syntheticName}});blockControlStatus(list,'Scoped-key reconciliation list',200);
 const matches=parseApiKeys(list.body).filter(k=>k.name===syntheticName);if(matches.length>1)blockProviderSpike('AMBIGUOUS_SCOPED_KEY_STATE','Multiple exact-name scoped keys found during reconciliation.');
 if(matches.length===1){const id=profileId(matches[0]!);if(!id)blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Reconciled API key is missing provider ID.');const revoked=await context.request({method:'DELETE',url:`/v1/api-keys/${encodeURIComponent(id)}`,safeMetadata:{path:'/v1/api-keys/{keyId}',method:'DELETE',purpose:'orphaned-unknown-create-cleanup',provider_key_id:id}});if(status(revoked)!==200)blockProviderSpike('SCOPED_KEY_CLEANUP_UNCONFIRMED','Orphaned scoped key could not be confirmed revoked.');}
 blockProviderSpike('UNKNOWN_SCOPED_KEY_CREATE_OUTCOME','Scoped key creation outcome was uncertain; no automatic retry was attempted.');
}

export function createP1T03KeyCreateCase(spec:KeySpec,syntheticName:string,providerEnvironment='authorized-internal-zernio-test-team',capture?:(key:P1T03CreatedKeyInternal)=>void):ProviderSpikeTestCase{
 const base=commonCase(`P1-T03-KEY-${spec.logicalKey}-CREATE`,3,['ZERNIO_API_KEY'],providerEnvironment);
 return {...base,testConfig:{logicalKey:spec.logicalKey,syntheticName,scope:'profiles',profileIds:[spec.profileId],permission:'read',expiresIn:EXPIRY_DAYS},execute:async context=>{
  let response:ProviderTransportResponse;
  try{response=await context.request({method:'POST',url:'/v1/api-keys',body:{name:syntheticName,expiresIn:EXPIRY_DAYS,scope:'profiles',profileIds:[spec.profileId],permission:'read'},safeMetadata:{path:'/v1/api-keys',method:'POST',logical_key:spec.logicalKey,synthetic_name:syntheticName,scope:'profiles',permitted_profile_id:spec.profileId,permission:'read',expires_in_days:EXPIRY_DAYS}});}catch(error){const c=errorCategory(error);if(c==='TIMEOUT'||c==='NETWORK_ERROR')return reconcileUnknownCreate(context,syntheticName);throw error;}
  const s=status(response);if(s!==201){if(s!==null&&s>=500)return reconcileUnknownCreate(context,syntheticName);if(s===401||s===403)blockProviderSpike('PROVIDER_AUTHORIZATION_BLOCKED','Scoped-key creation was not authorized.');if(s===429)blockProviderSpike('HTTP_429','Scoped-key creation was rate limited.');blockProviderSpike('PROVIDER_HTTP_BLOCKED',`Scoped-key creation returned unexpected status ${String(response.status)}.`);}
  const root=obj(response.body),apiKey=obj(root?.apiKey);if(!apiKey)blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Scoped-key create response is missing apiKey.');const providerKeyId=profileId(apiKey),secret=typeof apiKey.key==='string'&&apiKey.key?apiKey.key:null,ids=normalizedProfileIds(apiKey.profileIds),expiresAt=typeof apiKey.expiresAt==='string'&&apiKey.expiresAt?apiKey.expiresAt:null;
  if(!providerKeyId)blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Scoped-key create response is missing provider key ID.');if(!secret||apiKey.name!==syntheticName||apiKey.scope!=='profiles'||apiKey.permission!=='read'||!ids||ids.length!==1||ids[0]!==spec.profileId||!expiresAt){const cleanup=await context.request({method:'DELETE',url:`/v1/api-keys/${encodeURIComponent(providerKeyId)}`,safeMetadata:{path:'/v1/api-keys/{keyId}',method:'DELETE',purpose:'malformed-create-response-cleanup',provider_key_id:providerKeyId}});if(status(cleanup)!==200)blockProviderSpike('SCOPED_KEY_CLEANUP_UNCONFIRMED','Malformed scoped-key creation response returned an ID but cleanup could not be confirmed.');blockProviderSpike('MALFORMED_PROVIDER_RESPONSE','Scoped-key create response does not match requested restricted scope semantics.');}
  const metadata:P1T03KeyMetadata={logicalKey:spec.logicalKey,providerKeyId,syntheticName,scope:'profiles',permittedProfileId:spec.profileId,permission:'read',expiresAt,creationStatus:s,creationRequestId:requestId(response),creationLatencyMs:0};capture?.({metadata,secret});return {ok:true,providerKeyId,scope:'profiles',permittedProfileId:spec.profileId,permission:'read',expiresAt};
 },assert:async observation=>obj(observation)?.ok===true};
}

function probeRecord(response:ProviderTransportResponse,endpoint:string,own:KeySpec,foreign:KeySpec,profiles:JsonObject[]):P1T03ProbeRecord{const ids=profiles.map(profileId).filter((x):x is string=>Boolean(x)),names=profiles.map(profileName).filter((x):x is string=>Boolean(x));return {endpoint,status:status(response),requestId:requestId(response),visibleProfileCount:profiles.length,ownProfileVisible:ids.includes(own.profileId)||names.includes(own.profileName),foreignProfileVisible:ids.includes(foreign.profileId)||names.includes(foreign.profileName)};}
function probeStatus(response:ProviderTransportResponse,operation:string){blockTransient(response,operation);return status(response);}
function criticalLeak(profiles:JsonObject[],own:KeySpec){return profiles.some(p=>{const id=profileId(p);return id!==own.profileId;});}
function containsProfileReference(value:unknown,spec:KeySpec,seen=new WeakSet<object>()):boolean{if(typeof value==='string')return value.includes(spec.profileId)||value.includes(spec.profileName);if(!value||typeof value!=='object')return false;if(seen.has(value as object))return false;seen.add(value as object);if(Array.isArray(value))return value.some(x=>containsProfileReference(x,spec,seen));return Object.values(value as JsonObject).some(x=>containsProfileReference(x,spec,seen));}

export function createP1T03IsolationCase(own:KeySpec,foreign:KeySpec,providerEnvironment='authorized-internal-zernio-test-team',capture?:(outcome:P1T03IsolationOutcome)=>void):ProviderSpikeTestCase{
 const base=commonCase(`P1-T03-KEY-${own.logicalKey}-ISOLATION`,3,['P1_T03_SCOPED_KEY_RUNTIME'],providerEnvironment);
 return {...base,testConfig:{logicalKey:own.logicalKey,allowedProfileId:own.profileId,foreignProfileId:foreign.profileId},execute:async context=>{
  const probes:P1T03ProbeRecord[]=[];let fullVisibleProfileCount=0,ownProfileVisible=false,foreignProfileVisible=false,ownExactMatch=false,crossLookupIsolated=false,criticalLeakage=false;
  const finish=(ok:boolean)=>{const outcome:P1T03IsolationOutcome={logicalKey:own.logicalKey,fullVisibleProfileCount,ownProfileVisible,foreignProfileVisible,ownExactMatch,crossLookupIsolated,criticalLeakage,probes};capture?.(outcome);return {ok,criticalLeakage};};
  const list=await context.request({method:'GET',url:'/v1/profiles',safeMetadata:{path:'/v1/profiles',method:'GET',logical_key:own.logicalKey,probe:'full-visible-list',expected_profile_id:own.profileId}});const ls=probeStatus(list,'Scoped-key visible Profile list');if(ls!==200){probes.push(probeRecord(list,'GET /v1/profiles',own,foreign,[]));return finish(false);}const listProfiles=parseProfiles(list.body);const lr=probeRecord(list,'GET /v1/profiles',own,foreign,listProfiles);probes.push(lr);fullVisibleProfileCount=lr.visibleProfileCount;ownProfileVisible=lr.ownProfileVisible;foreignProfileVisible=lr.foreignProfileVisible;criticalLeakage=criticalLeak(listProfiles,own)||foreignProfileVisible;if(criticalLeakage)return finish(false);if(!ownProfileVisible||fullVisibleProfileCount!==1)return finish(false);
  const ownResponse=await context.request({method:'GET',url:`/v1/profiles?name=${encodeURIComponent(own.profileName)}`,safeMetadata:{path:'/v1/profiles',method:'GET',logical_key:own.logicalKey,probe:'own-exact-name',expected_profile_id:own.profileId}});const os=probeStatus(ownResponse,'Scoped-key own exact Profile lookup');if(os!==200){probes.push(probeRecord(ownResponse,`GET /v1/profiles?name=${own.profileName}`,own,foreign,[]));return finish(false);}const ownProfiles=parseProfiles(ownResponse.body),or=probeRecord(ownResponse,`GET /v1/profiles?name=${own.profileName}`,own,foreign,ownProfiles);probes.push(or);criticalLeakage=criticalLeak(ownProfiles,own)||or.foreignProfileVisible;if(criticalLeakage)return finish(false);ownExactMatch=ownProfiles.length===1&&profileId(ownProfiles[0]!)===own.profileId&&profileName(ownProfiles[0]!)===own.profileName;if(!ownExactMatch)return finish(false);
  const cross=await context.request({method:'GET',url:`/v1/profiles?name=${encodeURIComponent(foreign.profileName)}`,safeMetadata:{path:'/v1/profiles',method:'GET',logical_key:own.logicalKey,probe:'cross-profile-exact-name',foreign_profile_id:foreign.profileId}});const cs=probeStatus(cross,'Scoped-key cross Profile lookup');if(cs===403||cs===404){const cr=probeRecord(cross,`GET /v1/profiles?name=${foreign.profileName}`,own,foreign,[]);probes.push(cr);if(containsProfileReference(cross.body,foreign)){foreignProfileVisible=true;criticalLeakage=true;return finish(false);}crossLookupIsolated=true;return finish(true);}if(cs!==200){probes.push(probeRecord(cross,`GET /v1/profiles?name=${foreign.profileName}`,own,foreign,[]));return finish(false);}const crossProfiles=parseProfiles(cross.body),cr=probeRecord(cross,`GET /v1/profiles?name=${foreign.profileName}`,own,foreign,crossProfiles);probes.push(cr);foreignProfileVisible=foreignProfileVisible||cr.foreignProfileVisible;criticalLeakage=criticalLeak(crossProfiles,own)||cr.foreignProfileVisible;if(criticalLeakage)return finish(false);crossLookupIsolated=crossProfiles.length===0;return finish(crossLookupIsolated);
 },assert:async observation=>obj(observation)?.ok===true};
}

export function createP1T03RevokeCase(logicalKey:LogicalKey,providerKeyId:string,providerEnvironment='authorized-internal-zernio-test-team'):ProviderSpikeTestCase{const base=commonCase(`P1-T03-KEY-${logicalKey}-REVOKE`,1,['ZERNIO_API_KEY'],providerEnvironment);return {...base,execute:async context=>{const response=await context.request({method:'DELETE',url:`/v1/api-keys/${encodeURIComponent(providerKeyId)}`,safeMetadata:{path:'/v1/api-keys/{keyId}',method:'DELETE',logical_key:logicalKey,provider_key_id:providerKeyId,purpose:'temporary-key-cleanup'}});blockTransient(response,'Scoped-key revocation');return {ok:status(response)===200};},assert:async observation=>obj(observation)?.ok===true};}
export function createP1T03RevokedAuthCase(logicalKey:LogicalKey,providerEnvironment='authorized-internal-zernio-test-team',capture?:(valid:boolean)=>void):ProviderSpikeTestCase{const base=commonCase(`P1-T03-KEY-${logicalKey}-POST-REVOKE-AUTH`,1,['P1_T03_SCOPED_KEY_RUNTIME'],providerEnvironment);return {...base,execute:async context=>{const response=await context.request({method:'GET',url:'/v1/auth/verify',safeMetadata:{path:'/v1/auth/verify',method:'GET',logical_key:logicalKey,purpose:'post-revoke-auth-check'}});blockTransient(response,'Post-revoke credential verification');const s=status(response),body=obj(response.body),valid=s===200&&body?.valid===true;capture?.(valid);return {ok:s===401||(s===200&&body?.valid!==true),valid};},assert:async observation=>obj(observation)?.ok===true};}

function safeKeyRun(internal:P1T03CreatedKeyInternal,run:ProviderSpikeRunResult):P1T03KeyMetadata{return {...internal.metadata,creationStatus:typeof run.evidence.provider_status==='number'?run.evidence.provider_status:null,creationRequestId:run.evidence.provider_request_id,creationLatencyMs:run.evidence.latency_ms};}

export async function runP1T03(options:P1T03RunOptions={}):Promise<P1T03RunResult>{
 const live=options.live===true,env=options.env??process.env,providerEnvironment=options.providerEnvironment??'authorized-internal-zernio-test-team',counter={count:0,max:options.requestCeiling??LIVE_REQUEST_CEILING};
 const blank=(errorCategory:string):P1T03RunResult=>({liveEnabled:live,result:'BLOCKED',errorCategory,preflight:null,identityMatch:false,keyA:null,keyB:null,isolationA:null,isolationB:null,cleanup:[],crossProfileLeakageObserved:false,liveRequestCount:counter.count});if(!live)return blank('LIVE_OPT_IN_REQUIRED');
 const controlRaw=options.controlTransport??(env.ZERNIO_API_KEY?createZernioLiveTransport(env.ZERNIO_API_KEY):undefined);const control=controlRaw?aggregateBounded(controlRaw,counter):undefined;let identityMatch=false;
 const preflight=await runProviderSpikeCase(createP1T02TeamPreflightCase('live',env.ZERNIO_EXPECTED_USER_EMAIL,providerEnvironment,value=>{identityMatch=value.expectedIdentityMatch;}),{env,...(control?{transport:control}:{}),redactionSecrets:redactionSecrets(env)});
 const baseResult:Omit<P1T03RunResult,'result'|'errorCategory'|'keyA'|'keyB'|'isolationA'|'isolationB'|'cleanup'|'crossProfileLeakageObserved'|'liveRequestCount'>={liveEnabled:true,preflight,identityMatch};if(preflight.evidence.result!=='PASS')return {...baseResult,result:'BLOCKED',errorCategory:preflight.evidence.error_category,keyA:null,keyB:null,isolationA:null,isolationB:null,cleanup:[],crossProfileLeakageObserved:false,liveRequestCount:counter.count};
 const runTag=(options.runTag??randomUUID()).replace(/[^a-zA-Z0-9-]/g,'').slice(0,36),nameA=`aimm-p1-t03-profile-a-readonly-${runTag}`,nameB=`aimm-p1-t03-profile-b-readonly-${runTag}`;const internalABox:{value:P1T03CreatedKeyInternal|null}={value:null},internalBBox:{value:P1T03CreatedKeyInternal|null}={value:null},isolationABox:{value:P1T03IsolationOutcome|null}={value:null},isolationBBox:{value:P1T03IsolationOutcome|null}={value:null};let keyA:P1T03KeyMetadata|null=null,keyB:P1T03KeyMetadata|null=null,isolationA:P1T03IsolationOutcome|null=null,isolationB:P1T03IsolationOutcome|null=null;
 const createA=await runProviderSpikeCase(createP1T03KeyCreateCase(KEY_A,nameA,providerEnvironment,key=>{internalABox.value=key;}),{env,transport:control!,redactionSecrets:redactionSecrets(env)});const internalA=internalABox.value;if(createA.evidence.result!=='PASS'||!internalA)return {...baseResult,result:createA.evidence.result,errorCategory:createA.evidence.error_category,keyA:null,keyB:null,isolationA:null,isolationB:null,cleanup:[],crossProfileLeakageObserved:false,liveRequestCount:counter.count};keyA=safeKeyRun(internalA,createA);
 const cleanupKnown=async():Promise<{outcomes:P1T03CleanupOutcome[];confirmed:boolean}>=>{const entries=[internalABox.value,internalBBox.value].filter((x):x is P1T03CreatedKeyInternal=>Boolean(x)),revokeRuns=new Map<LogicalKey,ProviderSpikeRunResult>(),verifyRuns=new Map<LogicalKey,{run:ProviderSpikeRunResult;valid:boolean|null}>();for(const item of entries){const run=await runProviderSpikeCase(createP1T03RevokeCase(item.metadata.logicalKey,item.metadata.providerKeyId,providerEnvironment),{env,transport:control!,redactionSecrets:redactionSecrets(env)});revokeRuns.set(item.metadata.logicalKey,run);}for(const item of entries){let valid:boolean|null=null;const scopedRaw=options.scopedTransportFactory?options.scopedTransportFactory(item.secret):createZernioLiveTransport(item.secret),scoped=aggregateBounded(scopedRaw,counter),scopedEnv=runtimeScopedEnv(item.secret);const run=await runProviderSpikeCase(createP1T03RevokedAuthCase(item.metadata.logicalKey,providerEnvironment,v=>{valid=v;}),{env:scopedEnv,transport:scoped,redactionSecrets:[item.secret]});verifyRuns.set(item.metadata.logicalKey,{run,valid});}const outcomes=entries.map(item=>{const revoke=revokeRuns.get(item.metadata.logicalKey)!,verify=verifyRuns.get(item.metadata.logicalKey)!;const confirmed=revoke.evidence.result==='PASS'&&verify.run.evidence.result==='PASS'&&verify.valid===false;return {logicalKey:item.metadata.logicalKey,providerKeyId:item.metadata.providerKeyId,revokeResult:revoke.evidence.result,revokeStatus:revoke.evidence.provider_status,revokeRequestId:revoke.evidence.provider_request_id,postRevokeCredentialValid:verify.valid,verifyStatus:verify.run.evidence.provider_status,verifyRequestId:verify.run.evidence.provider_request_id,confirmed} satisfies P1T03CleanupOutcome;});return {outcomes,confirmed:outcomes.every(x=>x.confirmed)};};
 const finalize=async(result:'PASS'|'FAIL'|'BLOCKED',errorCategory:string|null,crossLeak:boolean)=>{const cleaned=await cleanupKnown();return {...baseResult,result:cleaned.confirmed?result:'BLOCKED',errorCategory:cleaned.confirmed?errorCategory:'SCOPED_KEY_CLEANUP_UNCONFIRMED',keyA,keyB,isolationA,isolationB,cleanup:cleaned.outcomes,crossProfileLeakageObserved:crossLeak,liveRequestCount:counter.count} satisfies P1T03RunResult;};
 const createB=await runProviderSpikeCase(createP1T03KeyCreateCase(KEY_B,nameB,providerEnvironment,key=>{internalBBox.value=key;}),{env,transport:control!,redactionSecrets:redactionSecrets(env)});const internalB=internalBBox.value;if(createB.evidence.result!=='PASS'||!internalB)return finalize(createB.evidence.result,createB.evidence.error_category,false);keyB=safeKeyRun(internalB,createB);if(keyA.providerKeyId===keyB.providerKeyId)return finalize('FAIL','SCOPED_KEY_IDS_NOT_DISTINCT',false);
 const scopedA=aggregateBounded(options.scopedTransportFactory?options.scopedTransportFactory(internalA.secret):createZernioLiveTransport(internalA.secret),counter),envA=runtimeScopedEnv(internalA.secret);const runA=await runProviderSpikeCase(createP1T03IsolationCase(KEY_A,KEY_B,providerEnvironment,value=>{isolationABox.value=value;}),{env:envA,transport:scopedA,redactionSecrets:[internalA.secret]});isolationA=isolationABox.value;if(runA.evidence.result!=='PASS')return finalize(runA.evidence.result,isolationA?.criticalLeakage?'CRITICAL_CROSS_PROFILE_SCOPE_LEAKAGE':runA.evidence.error_category,Boolean(isolationA?.criticalLeakage));
 const scopedB=aggregateBounded(options.scopedTransportFactory?options.scopedTransportFactory(internalB.secret):createZernioLiveTransport(internalB.secret),counter),envB=runtimeScopedEnv(internalB.secret);const runB=await runProviderSpikeCase(createP1T03IsolationCase(KEY_B,KEY_A,providerEnvironment,value=>{isolationBBox.value=value;}),{env:envB,transport:scopedB,redactionSecrets:[internalB.secret]});isolationB=isolationBBox.value;if(runB.evidence.result!=='PASS')return finalize(runB.evidence.result,isolationB?.criticalLeakage?'CRITICAL_CROSS_PROFILE_SCOPE_LEAKAGE':runB.evidence.error_category,Boolean(isolationB?.criticalLeakage));
 return finalize('PASS',null,false);
}

export const P1_T03_KEY_A=KEY_A;
export const P1_T03_KEY_B=KEY_B;
export const P1_T03_LIVE_REQUEST_CEILING=LIVE_REQUEST_CEILING;
