import { describe, expect, it, vi } from 'vitest';
import { P1_T04_ACCOUNT_ID, P1_T04_PAGE_ID, P1_T04_PROFILE_ID, runP1T04, type ProviderTransport, type ProviderTransportRequest, type ProviderTransportResponse } from '../../src/provider-spike/index.js';

const CONTROL='F01_CONTROL_SECRET', SCOPED='F01_SCOPED_SECRET', EMAIL='operator@example.invalid', NOW=new Date('2026-10-07T12:00:00.000Z');
const baseEnv={ZERNIO_API_KEY:CONTROL,ZERNIO_EXPECTED_USER_EMAIL:EMAIL,ZERNIO_P1_T04_EXPECTED_FACEBOOK_ACCOUNT_ID:P1_T04_ACCOUNT_ID,ZERNIO_P1_T04_EXPECTED_FACEBOOK_PAGE_ID:P1_T04_PAGE_ID,ZERNIO_P1_T04_ALLOW_PUBLIC_TEST:'true'};
type Kind='draft'|'scheduled'|'immediate';
type PageMode='expected'|'wrong'|'missing';
type Options={createPage?:Partial<Record<Kind,PageMode>>;readPage?:Partial<Record<Kind,PageMode>>;immediateFallback?:'expected-post-id'|'expected-url'|'wrong-post-id'|'wrong-url'|'none';readWrongContent?:Kind;deletedStillVisible?:Kind;immediateCreatePublishing?:boolean;deleteStatus?:200|204;};
interface StoredPost{id:string;kind:Kind;body:any;deleted:boolean;unpublished:boolean;}
function res(status:number,body:unknown={},id='req'):ProviderTransportResponse{return {status,headers:{'x-request-id':id},body};}
function kindOf(body:any):Kind{return body.publishNow===true?'immediate':body.scheduledFor?'scheduled':'draft';}
function pageFor(mode:PageMode|undefined){return mode==='missing'?null:mode==='wrong'?'999999999999999':P1_T04_PAGE_ID;}
function scenario(options:Options={}){
 const controlRequests:ProviderTransportRequest[]=[],scopedRequests:ProviderTransportRequest[]=[],posts=new Map<string,StoredPost>(),idem=new Map<string,string>(),attempts:Record<Kind,number>={draft:0,scheduled:0,immediate:0};let keyRevoked=false,next=1;
 const postBody=(stored:StoredPost,read:boolean)=>{const mode=(read?options.readPage:options.createPage)?.[stored.kind],pageId=pageFor(mode),entry:any={platform:'facebook',accountId:{_id:P1_T04_ACCOUNT_ID,platform:'facebook'},status:stored.kind==='immediate'?(stored.unpublished?'cancelled':'published'):'pending'};if(pageId)entry.platformSpecificData={pageId};if(stored.kind==='immediate'&&!pageId){const f=options.immediateFallback??'none';if(f==='expected-post-id')entry.platformPostId=`${P1_T04_PAGE_ID}_123456789`;if(f==='expected-url')entry.platformPostUrl=`https://www.facebook.com/${P1_T04_PAGE_ID}_123456789`;if(f==='wrong-post-id')entry.platformPostId='999999999999999_123456789';if(f==='wrong-url')entry.platformPostUrl='https://www.facebook.com/999999999999999_123456789';}
  let scheduledFor:string|undefined;if(stored.kind==='scheduled')scheduledFor=new Date(`${stored.body.scheduledFor}+03:00`).toISOString();const state=stored.kind==='draft'?'draft':stored.kind==='scheduled'?'scheduled':(!read&&options.immediateCreatePublishing?'publishing':'published');if(stored.kind==='immediate'&&!read&&options.immediateCreatePublishing)entry.status='pending';return {_id:stored.id,content:options.readWrongContent===stored.kind&&read?'WRONG':stored.body.content,status:state,...(scheduledFor?{scheduledFor,timezone:stored.body.timezone}:{}),platforms:[entry]};};
 const control:ProviderTransport={kind:'live',send:vi.fn(async request=>{controlRequests.push(request);if(request.method==='GET'&&request.url==='/v1/auth/verify')return res(200,{valid:true,email:EMAIL},'identity');if(request.method==='POST'&&request.url==='/v1/api-keys'){const b=request.body as any;return res(201,{apiKey:{id:'f01-key',name:b.name,key:SCOPED,scope:'profiles',profileIds:[P1_T04_PROFILE_ID],permission:'read-write',expiresAt:'2026-10-08T00:00:00Z'}},'key-create');}if(request.method==='DELETE'&&request.url==='/v1/api-keys/f01-key'){keyRevoked=true;return res(200,{message:'deleted'},'key-delete');}throw new Error(`unexpected control ${request.method} ${request.url}`);})};
 const scopedTransportFactory=(secret:string):ProviderTransport=>({kind:'live',send:vi.fn(async request=>{expect(secret).toBe(SCOPED);scopedRequests.push(request);if(request.method==='GET'&&request.url==='/v1/auth/verify')return keyRevoked?res(401,{error:'Unauthorized'},'revoked'):res(200,{valid:true},'valid');if(request.method==='GET'&&request.url?.startsWith('/v1/accounts?profileId='))return res(200,{accounts:[{_id:P1_T04_ACCOUNT_ID,platform:'facebook',profileId:{_id:P1_T04_PROFILE_ID}}]},'accounts');if(request.method==='GET'&&request.url===`/v1/accounts/${P1_T04_ACCOUNT_ID}/facebook-page`)return res(200,{pages:[{id:P1_T04_PAGE_ID,name:'Clothing Brand'}],selectedPageId:P1_T04_PAGE_ID},'page');if(request.method==='GET'&&request.url===`/v1/accounts/${P1_T04_ACCOUNT_ID}/health`)return res(200,{accountId:P1_T04_ACCOUNT_ID,platform:'facebook',status:'healthy',tokenStatus:{valid:true},permissions:{canPost:true}},'health');
  if(request.method==='POST'&&request.url==='/v1/posts'){const body=request.body as any,kind=kindOf(body),key=request.headers?.['Idempotency-Key']??'';attempts[kind]++;const existing=idem.get(key);if(existing){const stored=posts.get(existing)!;return res(200,{post:postBody(stored,false)},`replay-${kind}`);}const stored:StoredPost={id:`post-${next++}`,kind,body,deleted:false,unpublished:false};posts.set(stored.id,stored);idem.set(key,stored.id);return res(201,{post:postBody(stored,false)},`create-${kind}`);}
  const match=request.url?.match(/^\/v1\/posts\/([^/]+)$/);if(match&&request.method==='GET'){const id=decodeURIComponent(match[1]!),stored=posts.get(id);if(!stored||stored.deleted)return res(404,{error:'Not found'},`get-404-${id}`);return res(200,{post:postBody(stored,true)},`get-${stored.kind}`);}if(match&&request.method==='DELETE'){const id=decodeURIComponent(match[1]!),stored=posts.get(id);if(!stored)return res(404,{},'delete-missing');if(options.deletedStillVisible!==stored.kind)stored.deleted=true;return res(options.deleteStatus??200,{message:'deleted'},`delete-${stored.kind}`);}
  const unpublish=request.url?.match(/^\/v1\/posts\/([^/]+)\/unpublish$/);if(unpublish&&request.method==='POST'){const stored=posts.get(decodeURIComponent(unpublish[1]!));if(!stored)return res(404,{},'unpublish-missing');stored.unpublished=true;return res(200,{success:true},'unpublish');}throw new Error(`unexpected scoped ${request.method} ${request.url}`);})});
 return {control,scopedTransportFactory,controlRequests,scopedRequests,attempts,get keyRevoked(){return keyRevoked;}};
}
async function run(options:Options={},extra:Record<string,unknown>={}){const s=scenario(options);const result=await runP1T04({live:true,env:{...baseEnv},controlTransport:s.control,scopedTransportFactory:s.scopedTransportFactory,runTag:'f01-test',now:NOW,sleep:async()=>{},...extra});return {result,s};}
function deletes(s:ReturnType<typeof scenario>,kind:Kind){return s.scopedRequests.filter(r=>r.method==='DELETE'&&r.url?.startsWith('/v1/posts/')).length;}
function cleanupReads(s:ReturnType<typeof scenario>){return s.scopedRequests.filter(r=>r.method==='GET'&&/^\/v1\/posts\//.test(r.url??'')).length;}

describe('P1-T04-F01 exact Page attestation and emergency cleanup regressions',()=>{
 it('F01-T01 explicit wrong Page with correct account is Critical and cleanup executes',async()=>{const {result,s}=await run({createPage:{draft:'wrong'}});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_WRONG_PUBLISHING_TARGET');expect(result.wrongTargetObserved).toBe(true);expect(deletes(s,'draft')).toBeGreaterThan(0);expect(result.draft?.cleanupConfirmed).toBe(true);});
 it('F01-T02 wrong Page appearing only on read-back is Critical',async()=>{const {result}=await run({readPage:{draft:'wrong'}});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_WRONG_PUBLISHING_TARGET');expect(result.draft?.cleanupConfirmed).toBe(true);});
 it('F01-T03 correct account plus missing Page evidence cannot PASS',async()=>{const {result}=await run({createPage:{draft:'missing'}});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('PUBLISHING_PAGE_TARGET_UNCONFIRMED');});
 it('F01-T04 immediate post may attest expected Page from strict platformPostId fallback',async()=>{const {result}=await run({createPage:{immediate:'missing'},readPage:{immediate:'missing'},immediateFallback:'expected-post-id'});expect(result.result).toBe('PASS');expect(result.wrongTargetObserved).toBe(false);});
 it('F01-T05 wrong Page in platformPostId is Critical',async()=>{const {result}=await run({createPage:{immediate:'missing'},immediateFallback:'wrong-post-id'});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_WRONG_PUBLISHING_TARGET');});
 it('F01-T06 wrong Page in public URL is Critical',async()=>{const {result}=await run({createPage:{immediate:'missing'},immediateFallback:'wrong-url'});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_WRONG_PUBLISHING_TARGET');});
 it('F01-T07 draft missing Page attestation blocks all later stages',async()=>{const {result,s}=await run({createPage:{draft:'missing'}});expect(result.errorCategory).toBe('PUBLISHING_PAGE_TARGET_UNCONFIRMED');expect(s.attempts.scheduled).toBe(0);expect(s.attempts.immediate).toBe(0);const cleanupPhase=[...s.controlRequests,...s.scopedRequests].filter(r=>(r.safeMetadata as any)?.phase==='cleanup');expect(cleanupPhase.some(r=>r.method==='POST'&&r.url==='/v1/posts')).toBe(false);expect(cleanupPhase.some(r=>r.method==='POST'&&r.url==='/v1/api-keys')).toBe(false);});
 it('F01-T08 scheduled missing Page attestation blocks immediate create',async()=>{const {result,s}=await run({createPage:{scheduled:'missing'}});expect(result.errorCategory).toBe('PUBLISHING_PAGE_TARGET_UNCONFIRMED');expect(s.attempts.immediate).toBe(0);});
 it('F01-T09 emergency draft cleanup requires read-back and still-active draft is unconfirmed',async()=>{const {result}=await run({readWrongContent:'draft',deletedStillVisible:'draft'});expect(result.errorCategory).toBe('DRAFT_TEST_POST_CLEANUP_UNCONFIRMED');expect(result.draft?.cleanupConfirmed).toBe(false);expect(result.draft?.cleanupReadStatus).toBe(200);});
 it('F01-T10 emergency scheduled cleanup requires read-back and still-scheduled artifact is unconfirmed',async()=>{const {result}=await run({readWrongContent:'scheduled',deletedStillVisible:'scheduled'});expect(result.errorCategory).toBe('SCHEDULED_TEST_POST_CLEANUP_UNCONFIRMED');expect(result.scheduled?.cleanupConfirmed).toBe(false);expect(result.scheduled?.cleanupReadStatus).toBe(200);});
 it('F01-T11 successful emergency cleanup confirms DELETE plus GET terminal state',async()=>{const {result}=await run({readWrongContent:'draft',deleteStatus:204});expect(result.result).toBe('BLOCKED');expect(result.draft?.cleanupConfirmed).toBe(true);expect(result.draft?.cleanupStatus).toBe(204);expect(result.draft?.cleanupReadStatus).toBe(404);});
 it('F01-T12 cleanup DELETE and GET run after normal ceiling exhaustion using cleanup allowance',async()=>{const {result,s}=await run({}, {normalRequestCeiling:6});expect(result.errorCategory).toBe('REQUEST_LIMIT_EXCEEDED');expect(result.draft?.cleanupConfirmed).toBe(true);expect(result.cleanupRequestCount).toBeGreaterThanOrEqual(4);expect(deletes(s,'draft')).toBeGreaterThan(0);expect(cleanupReads(s)).toBeGreaterThan(0);expect(s.attempts.scheduled).toBe(0);expect(s.attempts.immediate).toBe(0);const cleanupPhase=[...s.controlRequests,...s.scopedRequests].filter(r=>(r.safeMetadata as any)?.phase==='cleanup');expect(cleanupPhase.some(r=>r.method==='POST'&&r.url==='/v1/posts')).toBe(false);expect(cleanupPhase.some(r=>r.method==='POST'&&r.url==='/v1/api-keys')).toBe(false);});
 it('F01-T13 strengthened target semantics preserve the existing happy path',async()=>{const {result}=await run();expect(result.result).toBe('PASS');expect(result.liveRequestCount).toBeLessThanOrEqual(22);});
 it('Extra immediate fallback is not accepted before provider state is published',async()=>{const {result}=await run({createPage:{immediate:'missing'},immediateFallback:'expected-post-id',immediateCreatePublishing:true});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('PUBLISHING_PAGE_TARGET_UNCONFIRMED');});
 it('Extra deterministic fix run never exposes configured secrets',async()=>{const {result}=await run({createPage:{draft:'missing'}});const serialized=JSON.stringify(result);expect(serialized).not.toContain(CONTROL);expect(serialized).not.toContain(SCOPED);expect(serialized).not.toContain(EMAIL);});
});
