import { describe, expect, it, vi } from 'vitest';
import { P1_T04_ACCOUNT_ID, P1_T04_PAGE_ID, P1_T04_PROFILE_ID, runP1T04, type ProviderTransport, type ProviderTransportRequest, type ProviderTransportResponse } from '../../src/provider-spike/index.js';

const CONTROL='P1T04_CONTROL_SECRET_SENTINEL', SCOPED='P1T04_SCOPED_SECRET_SENTINEL', EMAIL='trusted.operator@example.invalid', NOW=new Date('2026-10-07T12:00:00.000Z');
const baseEnv={ZERNIO_API_KEY:CONTROL,ZERNIO_EXPECTED_USER_EMAIL:EMAIL,ZERNIO_P1_T04_EXPECTED_FACEBOOK_ACCOUNT_ID:P1_T04_ACCOUNT_ID,ZERNIO_P1_T04_EXPECTED_FACEBOOK_PAGE_ID:P1_T04_PAGE_ID,ZERNIO_P1_T04_ALLOW_PUBLIC_TEST:'true'};
type Kind='draft'|'scheduled'|'immediate';
type Options={identityEmail?:string;missingAccount?:boolean;wrongProfile?:boolean;profilePlain?:boolean;missingPage?:boolean;selectedWrongPage?:boolean;healthBad?:boolean;duplicateDraftReplay?:boolean;replay422?:boolean;readWrongContent?:Kind;wrongTargetKind?:Kind;badCreateState?:Kind;scheduledReturnShiftHours?:number;cleanupFail?:Kind;publicCleanupStillPublished?:boolean;networkOnKind?:Kind;fiveHundredOnKind?:Kind;rateLimitOnKind?:Kind;keyCleanupFail?:boolean;postRevokeStillValid?:boolean;malformedKey?:boolean;};
interface StoredPost{id:string;kind:Kind;body:any;deleted:boolean;unpublished:boolean;}
function response(status:number,body:unknown={},id='req'):ProviderTransportResponse{return {status,headers:{'x-request-id':id},body};}
function kindOf(body:any):Kind{return body.publishNow===true?'immediate':body.scheduledFor?'scheduled':'draft';}
function accountEntry(pageId=P1_T04_PAGE_ID,status='pending'){return {platform:'facebook',accountId:{_id:P1_T04_ACCOUNT_ID,platform:'facebook'},status,platformSpecificData:{pageId}};}
function postBody(stored:StoredPost,options:Options,read=false){const kind=stored.kind,b=stored.body;let status=kind==='draft'?'draft':kind==='scheduled'?'scheduled':'published',platformStatus=kind==='immediate'?'published':'pending';if(options.badCreateState===kind&&!read){status=kind==='draft'?'scheduled':kind==='scheduled'?'draft':'published';if(kind==='immediate')platformStatus='pending';}const page=options.wrongTargetKind===kind?P1_T04_PAGE_ID:'1387424501114639';const acct=options.wrongTargetKind===kind?'wrong-account':P1_T04_ACCOUNT_ID;const entry={platform:'facebook',accountId:{_id:acct,platform:'facebook'},status:stored.unpublished?'cancelled':platformStatus,platformSpecificData:{pageId:page},...(kind==='immediate'?{platformPostId:'fb-post-123',platformPostUrl:'https://facebook.example/test-post',publishedAt:'2026-10-07T12:00:05.000Z'}:{})};let scheduledFor:any=undefined;if(kind==='scheduled'){const requested=new Date(`${b.scheduledFor}+03:00`);if(options.scheduledReturnShiftHours)requested.setUTCHours(requested.getUTCHours()+options.scheduledReturnShiftHours);scheduledFor=requested.toISOString();}return {_id:stored.id,content:options.readWrongContent===kind&&read?'WRONG CONTENT':b.content,status,...(scheduledFor?{scheduledFor,timezone:b.timezone}:{}),...(kind==='immediate'?{publishedAt:'2026-10-07T12:00:05.000Z'}:{}),platforms:[entry]};}
function scenario(options:Options={}){
 const controlRequests:ProviderTransportRequest[]=[],scopedRequests:ProviderTransportRequest[]=[],posts=new Map<string,StoredPost>(),idem=new Map<string,{body:string;id:string}>(),postAttempts:Record<Kind,number>={draft:0,scheduled:0,immediate:0};let keyRevoked=false,keyCreated=false,next=1;
 const reqId=(prefix:string)=>`${prefix}-${controlRequests.length+scopedRequests.length+1}`;
 const control:ProviderTransport={kind:'live',send:vi.fn(async request=>{controlRequests.push(request);if(request.method==='GET'&&request.url==='/v1/auth/verify')return response(200,{valid:true,email:options.identityEmail??EMAIL},'identity-req');if(request.method==='POST'&&request.url==='/v1/api-keys'){keyCreated=true;const body=request.body as any;if(options.malformedKey)return response(201,{apiKey:{id:'publishing-key',name:body.name,scope:'profiles',profileIds:[P1_T04_PROFILE_ID],permission:'read-write',expiresAt:'2026-10-08T00:00:00Z'}},'key-create');return response(201,{apiKey:{id:'publishing-key',name:body.name,key:SCOPED,scope:'profiles',profileIds:[{_id:P1_T04_PROFILE_ID}],permission:'read-write',expiresAt:'2026-10-08T00:00:00Z'}},'key-create');}if(request.method==='GET'&&request.url==='/v1/api-keys')return response(200,{apiKeys:keyCreated&&!keyRevoked?[{id:'publishing-key',name:'aimm-p1-t04-publishing-offline-test',scope:'profiles',profileIds:[P1_T04_PROFILE_ID],permission:'read-write'}]:[]},'key-list');if(request.method==='DELETE'&&request.url==='/v1/api-keys/publishing-key'){if(options.keyCleanupFail)return response(500,{error:'fail'},'key-delete-fail');keyRevoked=true;return response(200,{message:'deleted'},'key-delete');}throw new Error(`unexpected control ${request.method} ${request.url}`);})};
 const scopedTransportFactory=(secret:string):ProviderTransport=>({kind:'live',send:vi.fn(async request=>{expect(secret).toBe(SCOPED);scopedRequests.push(request);if(request.method==='GET'&&request.url==='/v1/auth/verify')return options.postRevokeStillValid?response(200,{valid:true},'post-revoke-valid'):keyRevoked?response(401,{error:'Unauthorized'},'post-revoke-401'):response(200,{valid:true},'scoped-valid');if(keyRevoked)return response(401,{error:'Unauthorized'},'revoked');
  if(request.method==='GET'&&request.url?.startsWith('/v1/accounts?profileId=')){if(options.missingAccount)return response(200,{accounts:[]},'accounts');const profileId=options.wrongProfile?'wrong-profile':P1_T04_PROFILE_ID;return response(200,{accounts:[{_id:P1_T04_ACCOUNT_ID,platform:'facebook',username:'Clothing Brand',profileId:options.profilePlain?profileId:{_id:profileId,name:'aimm-p1-t02-profile-a'}}]},'accounts');}
  if(request.method==='GET'&&request.url===`/v1/accounts/${P1_T04_ACCOUNT_ID}/facebook-page`){const pages=options.missingPage?[{id:'other-page',name:'Other'}]:[{id:P1_T04_PAGE_ID,name:'Clothing Brand'}];return response(200,{pages,selectedPageId:options.selectedWrongPage?'other-page':P1_T04_PAGE_ID,cached:true},'page');}
  if(request.method==='GET'&&request.url===`/v1/accounts/${P1_T04_ACCOUNT_ID}/health`)return response(200,{accountId:P1_T04_ACCOUNT_ID,platform:'facebook',status:options.healthBad?'error':'healthy',tokenStatus:{valid:!options.healthBad},permissions:{canPost:!options.healthBad,posting:[]},issues:[]},'health');
  if(request.method==='POST'&&request.url==='/v1/posts'){const body=request.body as any,kind=kindOf(body),key=request.headers?.['Idempotency-Key']??'',serialized=JSON.stringify(body);postAttempts[kind]++;if(options.rateLimitOnKind===kind&&postAttempts[kind]===1)return response(429,{error:'rate limit'},`429-${kind}`);const existing=idem.get(key);if(existing){if(options.replay422&&kind==='draft')return response(422,{error:'idempotency body mismatch'},'draft-422');if(existing.body!==serialized)return response(422,{error:'idempotency body mismatch'},'changed-body');if(options.duplicateDraftReplay&&kind==='draft'){const duplicate:StoredPost={id:`post-${next++}`,kind,body,deleted:false,unpublished:false};posts.set(duplicate.id,duplicate);return response(201,{post:postBody(duplicate,options,false)},'draft-duplicate');}const stored=posts.get(existing.id)!;return response(200,{post:postBody(stored,options,false)},`replay-${kind}`);}
   const stored:StoredPost={id:`post-${next++}`,kind,body,deleted:false,unpublished:false};posts.set(stored.id,stored);idem.set(key,{body:serialized,id:stored.id});if(options.networkOnKind===kind&&postAttempts[kind]===1)throw new Error('simulated network disconnect');if(options.fiveHundredOnKind===kind&&postAttempts[kind]===1)return response(500,{error:'uncertain'},`500-${kind}`);return response(201,{post:postBody(stored,options,false)},`create-${kind}`);}
  const postMatch=request.url?.match(/^\/v1\/posts\/([^/]+)$/);if(postMatch&&request.method==='GET'){const id=decodeURIComponent(postMatch[1]!),stored=posts.get(id);if(!stored||stored.deleted)return response(404,{error:'Not found'},`get-404-${id}`);return response(200,{post:postBody(stored,options,true)},`get-${stored.kind}`);}if(postMatch&&request.method==='DELETE'){const id=decodeURIComponent(postMatch[1]!),stored=posts.get(id);if(!stored)return response(404,{error:'Not found'},'delete-missing');if(options.cleanupFail===stored.kind)return response(500,{error:'cleanup fail'},`delete-fail-${stored.kind}`);stored.deleted=true;return response(200,{message:'deleted'},`delete-${stored.kind}`);}
  const unpublish=request.url?.match(/^\/v1\/posts\/([^/]+)\/unpublish$/);if(unpublish&&request.method==='POST'){const id=decodeURIComponent(unpublish[1]!),stored=posts.get(id);if(!stored)return response(404,{error:'Not found'},'unpublish-missing');if(options.cleanupFail==='immediate')return response(500,{error:'cleanup fail'},'unpublish-fail');if(!options.publicCleanupStillPublished)stored.unpublished=true;return response(200,{success:true},'unpublish');}throw new Error(`unexpected scoped ${request.method} ${request.url}`);})});
 return {control,scopedTransportFactory,controlRequests,scopedRequests,posts,postAttempts,get keyRevoked(){return keyRevoked;}};
}
function run(options:Options={},envOverrides:Record<string,string|undefined>={},runOptions:Record<string,unknown>={}){const s=scenario(options),env={...baseEnv,...envOverrides} as NodeJS.ProcessEnv;for(const [k,v] of Object.entries(env))if(v===undefined)delete env[k];return runP1T04({live:true,env,controlTransport:s.control,scopedTransportFactory:s.scopedTransportFactory,runTag:'offline-test',now:NOW,sleep:async()=>{},...runOptions}).then(result=>({result,s}));}
function postRequests(s:ReturnType<typeof scenario>){return s.scopedRequests.filter(r=>r.method==='POST'&&r.url==='/v1/posts');}

describe('P1-T04 Zernio publishing offline regressions',()=>{
 it('T04-01 default execution offline makes zero provider calls',async()=>{const send=vi.fn();const r=await runP1T04({controlTransport:{kind:'live',send} as ProviderTransport});expect(r.errorCategory).toBe('LIVE_OPT_IN_REQUIRED');expect(send).not.toHaveBeenCalled();});
 it('T04-02 missing control-plane credential blocks before mutation',async()=>{const {result,s}=await run({}, {ZERNIO_API_KEY:undefined});expect(result.result).toBe('BLOCKED');expect(result.preflight?.evidence.error_category).toBe('MISSING_LIVE_CREDENTIAL');expect(s.controlRequests).toHaveLength(0);});
 it('T04-03 missing expected identity blocks before mutation',async()=>{const {result,s}=await run({}, {ZERNIO_EXPECTED_USER_EMAIL:undefined});expect(result.result).toBe('BLOCKED');expect(result.preflight?.evidence.error_category).toBe('EXPECTED_PROVIDER_IDENTITY_MISSING');expect(s.controlRequests.filter(x=>x.method==='POST')).toHaveLength(0);});
 it('T04-04 identity mismatch blocks before mutation',async()=>{const {result,s}=await run({identityEmail:'other@example.invalid'});expect(result.errorCategory).toBe('PROVIDER_TARGET_IDENTITY_MISMATCH');expect(s.controlRequests.filter(x=>x.method==='POST')).toHaveLength(0);});
 it('T04-05 missing expected account target blocks before provider calls',async()=>{const {result,s}=await run({}, {ZERNIO_P1_T04_EXPECTED_FACEBOOK_ACCOUNT_ID:undefined});expect(result.errorCategory).toBe('EXPECTED_PUBLISHING_ACCOUNT_NOT_FOUND');expect(s.controlRequests).toHaveLength(0);});
 it('T04-06 missing expected Page target blocks before provider calls',async()=>{const {result,s}=await run({}, {ZERNIO_P1_T04_EXPECTED_FACEBOOK_PAGE_ID:undefined});expect(result.errorCategory).toBe('EXPECTED_FACEBOOK_PAGE_NOT_FOUND');expect(s.controlRequests).toHaveLength(0);});
 it('T04-07 public-test authorization not true blocks mutation',async()=>{const {result,s}=await run({}, {ZERNIO_P1_T04_ALLOW_PUBLIC_TEST:'false'});expect(result.errorCategory).toBe('PUBLIC_TEST_NOT_AUTHORIZED');expect(s.controlRequests).toHaveLength(0);});
 it('T04-08 temporary key is Profile-A-only read-write with bounded expiry',async()=>{const {result,s}=await run();expect(result.result).toBe('PASS');const req=s.controlRequests.find(r=>r.method==='POST'&&r.url==='/v1/api-keys')!;expect(req.body).toMatchObject({scope:'profiles',profileIds:[P1_T04_PROFILE_ID],permission:'read-write',expiresIn:1});expect(result.key?.permission).toBe('read-write');});
 it('T04-09 temporary key secret never leaks',async()=>{const {result}=await run();expect(JSON.stringify(result)).not.toContain(SCOPED);expect(JSON.stringify(result)).not.toContain(CONTROL);expect(JSON.stringify(result)).not.toContain(EMAIL);});
 it('T04-10 account response _id is correctly normalized',async()=>{const {result}=await run();expect(result.target?.accountId).toBe(P1_T04_ACCOUNT_ID);});
 it('T04-11 profileId object response is correctly normalized',async()=>{const {result}=await run();expect(result.target?.profileId).toBe(P1_T04_PROFILE_ID);});
 it('T04-12 expected account must equal frozen account ID',async()=>{const {result}=await run({missingAccount:true});expect(result.result).toBe('BLOCKED');expect(result.steps.some(x=>x.errorCategory==='EXPECTED_PUBLISHING_ACCOUNT_NOT_FOUND')).toBe(true);});
 it('T04-13 expected Profile must equal frozen Profile A ID',async()=>{const {result}=await run({profilePlain:true});expect(result.result).toBe('PASS');expect(result.target?.profileId).toBe(P1_T04_PROFILE_ID);});
 it('T04-14 wrong Profile/account is critical before post create',async()=>{const {result,s}=await run({wrongProfile:true});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_WRONG_PUBLISHING_TARGET');expect(postRequests(s)).toHaveLength(0);});
 it('T04-15 expected Page must equal frozen Page ID',async()=>{const {result}=await run();expect(result.target?.pageId).toBe(P1_T04_PAGE_ID);expect(result.target?.pageMatch).toBe(true);});
 it('T04-16 no default/first-Page fallback',async()=>{const {result,s}=await run({missingPage:true});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('EXPECTED_FACEBOOK_PAGE_NOT_FOUND');expect(postRequests(s)).toHaveLength(0);});
 it('T04-17 draft create validates provider post ID and draft state',async()=>{const {result}=await run();expect(result.draft?.postId).toBeTruthy();expect(result.draft?.createStatus).toBe(201);});
 it('T04-18 draft read-back validates exact target and content',async()=>{const {result}=await run({readWrongContent:'draft'});expect(result.result).toBe('BLOCKED');expect(result.immediate).toBeNull();});
 it('T04-19 same body plus same Idempotency-Key returns same logical post',async()=>{const {result,s}=await run();expect(result.draft?.sameLogicalPost).toBe(true);expect(result.draft?.duplicate).toBe(false);const reqs=postRequests(s).filter(r=>kindOf(r.body)==='draft');expect(reqs[0]?.headers?.['Idempotency-Key']).toBe(reqs[1]?.headers?.['Idempotency-Key']);expect(reqs[0]?.body).toEqual(reqs[1]?.body);});
 it('T04-20 duplicate logical post is critical',async()=>{const {result}=await run({duplicateDraftReplay:true});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_DUPLICATE_CONFIRMED_PUBLISH');expect(result.duplicateConfirmedPublishObserved).toBe(true);});
 it('T04-21 same Idempotency-Key changed-body rejection fails safely',async()=>{const {result}=await run({replay422:true});expect(result.result).toBe('BLOCKED');expect(result.draft?.cleanupConfirmed).toBe(true);});
 it('T04-22 draft cleanup is confirmed',async()=>{const {result}=await run();expect(result.draft?.cleanupConfirmed).toBe(true);expect(result.draft?.cleanupReadStatus).toBe(404);});
 it('T04-23 scheduled create uses at least 48h future schedule',async()=>{const {result,s}=await run();expect(result.result).toBe('PASS');const req=postRequests(s).find(r=>kindOf(r.body)==='scheduled')!;const wall=(req.body as any).scheduledFor;expect(new Date(`${wall}+03:00`).getTime()-NOW.getTime()).toBeGreaterThanOrEqual(48*3600_000);});
 it('T04-24 schedule uses Africa/Cairo semantics',async()=>{const {s}=await run();const req=postRequests(s).find(r=>kindOf(r.body)==='scheduled')!;expect((req.body as any).timezone).toBe('Africa/Cairo');});
 it('T04-25 scheduled read-back must match normalized schedule',async()=>{const {result}=await run({scheduledReturnShiftHours:1});expect(result.result).toBe('BLOCKED');expect(result.immediate).toBeNull();});
 it('T04-26 scheduled cleanup required before public test',async()=>{const {result,s}=await run({cleanupFail:'scheduled'});expect(result.result).toBe('BLOCKED');expect(s.postAttempts.immediate).toBe(0);});
 it('T04-27 immediate public create happens at most once',async()=>{const {result,s}=await run();expect(result.result).toBe('PASS');expect(s.postAttempts.immediate).toBe(1);});
 it('T04-28 published response requires platform-level published state',async()=>{const {result}=await run({badCreateState:'immediate'});expect(result.result).toBe('BLOCKED');});
 it('T04-29 wrong target is classified Critical',async()=>{const {result}=await run({wrongTargetKind:'immediate'});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_WRONG_PUBLISHING_TARGET');expect(result.wrongTargetObserved).toBe(true);});
 it('T04-30 published read-back matches the exact post',async()=>{const {result}=await run();expect(result.immediate?.readStatus).toBe(200);expect(result.immediate?.platformPostId).toBe('fb-post-123');});
 it('T04-31 public cleanup executes',async()=>{const {result,s}=await run();expect(result.immediate?.cleanupConfirmed).toBe(true);expect(s.scopedRequests.some(r=>r.method==='POST'&&r.url?.endsWith('/unpublish'))).toBe(true);});
 it('T04-32 public cleanup requires read-back',async()=>{const {result,s}=await run();expect(result.immediate?.cleanupReadStatus).toBe(200);const id=result.immediate?.postId;expect(s.scopedRequests.some(r=>r.method==='GET'&&r.url===`/v1/posts/${id}`)).toBe(true);});
 it('T04-33 cleanup failure prevents PASS',async()=>{const {result}=await run({publicCleanupStillPublished:true});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('PUBLISHED_TEST_POST_CLEANUP_UNCONFIRMED');});
 it('T04-34 timeout/network/5xx reuse the same logical Idempotency-Key',async()=>{const {result,s}=await run({networkOnKind:'draft'});expect(result.result).toBe('PASS');const reqs=postRequests(s).filter(r=>kindOf(r.body)==='draft');expect(new Set(reqs.map(r=>r.headers?.['Idempotency-Key'])).size).toBe(1);expect(s.postAttempts.draft).toBe(3);});
 it('T04-35 429 has no automatic retry',async()=>{const {result,s}=await run({rateLimitOnKind:'draft'});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('PROVIDER_RATE_LIMITED');expect(s.postAttempts.draft).toBe(1);});
 it('T04-36 normal request ceiling is enforced',async()=>{const {result}=await run({}, {}, {normalRequestCeiling:5});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('REQUEST_LIMIT_EXCEEDED');expect(result.normalRequestCount).toBe(5);});
 it('T04-37 safety cleanup remains allowed after normal ceiling',async()=>{const {result,s}=await run({}, {}, {normalRequestCeiling:5});expect(result.cleanupRequestCount).toBeGreaterThan(0);expect(result.keyCleanup?.confirmed).toBe(true);expect(s.keyRevoked).toBe(true);});
 it('T04-38 temporary publishing key is revoked',async()=>{const {result,s}=await run();expect(result.result).toBe('PASS');expect(result.keyCleanup?.confirmed).toBe(true);expect(s.keyRevoked).toBe(true);});
 it('T04-39 revoked key authentication fails',async()=>{const {result}=await run();expect(result.keyCleanup?.revokedKeyValid).toBe(false);expect(result.keyCleanup?.verifyStatus).toBe(401);});
 it('T04-40 existing P1-T01/P1-T02/P1-T03 behavior remains compatible',async()=>{const {result}=await run();expect(result.result).toBe('PASS');expect(result.liveRequestCount).toBeLessThanOrEqual(22);});
 it('extra uncertain 5xx create safely replays with same idempotency key',async()=>{const {result,s}=await run({fiveHundredOnKind:'scheduled'});expect(result.result).toBe('PASS');const reqs=postRequests(s).filter(r=>kindOf(r.body)==='scheduled');expect(new Set(reqs.map(r=>r.headers?.['Idempotency-Key'])).size).toBe(1);});
 it('extra unhealthy account blocks before any post mutation',async()=>{const {result,s}=await run({healthBad:true});expect(result.errorCategory).toBe('PUBLISHING_ACCOUNT_NOT_HEALTHY');expect(postRequests(s)).toHaveLength(0);});
 it('extra selected Page mismatch blocks with no fallback',async()=>{const {result,s}=await run({selectedWrongPage:true});expect(result.errorCategory).toBe('EXPECTED_FACEBOOK_PAGE_NOT_FOUND');expect(postRequests(s)).toHaveLength(0);});
 it('extra key cleanup failure prevents PASS',async()=>{const {result}=await run({keyCleanupFail:true,postRevokeStillValid:true});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('PUBLISHING_KEY_CLEANUP_UNCONFIRMED');});
});
