import { describe, expect, it, vi } from 'vitest';
import { createP1T02ProfileCase, P1_T02_PROFILE_A, P1_T02_PROFILE_B, runP1T02Profiles, runProviderSpikeCase, type P1T02ProfileOutcome, type ProviderTransport, type ProviderTransportRequest, type ProviderTransportResponse } from '../../src/provider-spike/index.js';

const SENTINEL='P1T02_FAKE_ZERNIO_SECRET_SENTINEL';
const EXPECTED_EMAIL='trusted-operator@example.test';
const env={ZERNIO_API_KEY:SENTINEL,ZERNIO_EXPECTED_USER_EMAIL:EXPECTED_EMAIL};
function scripted(responses:Array<ProviderTransportResponse|Error|(()=>Promise<ProviderTransportResponse>)>){const requests:ProviderTransportRequest[]=[];const send=vi.fn(async(request:ProviderTransportRequest)=>{requests.push(request);const next=responses.shift();if(typeof next==='function')return next();if(next instanceof Error)throw next;if(!next)throw new Error('Unexpected transport call');return next;});return {transport:{kind:'live' as const,send},requests,send};}
function list(name:string,id?:string,headers:Record<string,string>={}):ProviderTransportResponse{return {status:200,headers,body:{profiles:id?[{_id:id,name}]:[]}};}
function created(name:string,id:string):ProviderTransportResponse{return {status:201,headers:{'x-request-id':`create-${id}`},body:{profile:{_id:id,name}}};}
function verified(email=EXPECTED_EMAIL):ProviderTransportResponse{return {status:200,headers:{'x-request-id':'identity-ok'},body:{valid:true,userId:'user-test',authType:'api_key',scope:null,email}};}
function profileRun(spec:typeof P1_T02_PROFILE_A|typeof P1_T02_PROFILE_B,responses:Array<ProviderTransportResponse|Error|(()=>Promise<ProviderTransportResponse>)>,timeoutMs?:number){const mock=scripted(responses);const box:{value:P1T02ProfileOutcome|null}={value:null};const test=createP1T02ProfileCase(spec,'live','mock-zernio',value=>{box.value=value;});if(timeoutMs!==undefined)test.timeoutMs=timeoutMs;return runProviderSpikeCase(test,{env,transport:mock.transport}).then(run=>({run,outcome:box.value,mock}));}

describe('P1-T02 Zernio profile provisioning offline regressions',()=>{
 it('T02-01 default/non-live execution makes zero external requests',async()=>{const send=vi.fn();const result=await runP1T02Profiles({transport:{kind:'live',send} as ProviderTransport});expect(result.liveEnabled).toBe(false);expect(result.errorCategory).toBe('LIVE_OPT_IN_REQUIRED');expect(send).not.toHaveBeenCalled();});
 it('T02-02 missing credential blocks before live transport',async()=>{const send=vi.fn(async()=>({status:200}));const result=await runP1T02Profiles({live:true,env:{},transport:{kind:'live',send}});expect(result.result).toBe('BLOCKED');expect(result.preflight?.evidence.error_category).toBe('MISSING_LIVE_CREDENTIAL');expect(send).not.toHaveBeenCalled();});
 it('T02-03 failed authorized-team preflight prevents Profile creation',async()=>{const mock=scripted([{status:403,headers:{'x-request-id':'auth403'},body:{error:'forbidden'}}]);const result=await runP1T02Profiles({live:true,env,transport:mock.transport});expect(result.result).toBe('BLOCKED');expect(result.preflight?.evidence.error_category).toBe('PROVIDER_AUTHORIZATION_BLOCKED');expect(mock.send).toHaveBeenCalledTimes(1);expect(mock.requests[0]?.url).toBe('/v1/auth/verify');});
 it('T02-04 exact-name preflight existing Profile does not POST',async()=>{const {run,outcome,mock}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name,'profile-a'),list(P1_T02_PROFILE_A.name,'profile-a')]);expect(run.evidence.result).toBe('PASS');expect(outcome?.reconciledExisting).toBe(true);expect(mock.requests.every(r=>r.method==='GET')).toBe(true);});
 it('T02-05 absent Profile triggers exactly one create POST',async()=>{const {run,mock}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name),created(P1_T02_PROFILE_A.name,'profile-a'),list(P1_T02_PROFILE_A.name,'profile-a')]);expect(run.evidence.result).toBe('PASS');expect(mock.requests.filter(r=>r.method==='POST')).toHaveLength(1);expect(mock.requests.find(r=>r.method==='POST')?.headers?.['Idempotency-Key']).toBeTruthy();});
 it('T02-06 successful create is followed by read-back verification',async()=>{const {run,outcome,mock}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name),created(P1_T02_PROFILE_A.name,'profile-a'),list(P1_T02_PROFILE_A.name,'profile-a')]);expect(run.evidence.result).toBe('PASS');expect(outcome?.profileId).toBe('profile-a');expect(outcome?.createdThisRun).toBe(true);expect(mock.requests.at(-1)?.method).toBe('GET');});
 it('T02-07 Profile A and B must resolve to distinct IDs',async()=>{const profiles=new Map<string,string>();const transport:ProviderTransport={kind:'live',send:async request=>{if(request.url==='/v1/auth/verify')return verified();if(request.method==='GET'&&request.url?.startsWith('/v1/profiles?name=')){const name=decodeURIComponent(request.url.split('=')[1]??'');return list(name,profiles.get(name));}if(request.method==='POST'){const body=request.body as {name:string};const id=body.name.endsWith('-a')?'profile-a':'profile-b';profiles.set(body.name,id);return created(body.name,id);}throw new Error('unexpected');}};const result=await runP1T02Profiles({live:true,env,transport});expect(result.result).toBe('PASS');expect(result.identity?.expectedIdentityMatch).toBe(true);expect(result.distinctProfileIds).toBe(true);expect(result.profileA?.outcome?.profileId).toBe('profile-a');expect(result.profileB?.outcome?.profileId).toBe('profile-b');});
 it('T02-08 natural 409 reconciles exact name without renamed duplicate',async()=>{const {run,outcome,mock}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name),{status:409,headers:{'x-request-id':'dup'},body:{details:{existingProfileId:'profile-a'}}},list(P1_T02_PROFILE_A.name,'profile-a')]);expect(run.evidence.result).toBe('PASS');expect(outcome?.reconciledExisting).toBe(true);expect(mock.requests.filter(r=>r.method==='POST')).toHaveLength(1);expect(outcome?.expectedProfileName).toBe(P1_T02_PROFILE_A.name);});
 it('T02-09 timeout create is not blindly retried and reconciles with GET',async()=>{const hanging=()=>new Promise<ProviderTransportResponse>(()=>{});const {run,outcome,mock}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name),hanging,list(P1_T02_PROFILE_A.name,'profile-a')],20);expect(run.evidence.result).toBe('PASS');expect(outcome?.reconciledAfterUncertainCreate).toBe(true);expect(mock.requests.filter(r=>r.method==='POST')).toHaveLength(1);expect(mock.requests.filter(r=>r.method==='GET')).toHaveLength(2);});
 it('T02-10 unresolved ambiguous create becomes BLOCKED/UNKNOWN',async()=>{const {run,mock}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name),new Error('ECONNRESET'),list(P1_T02_PROFILE_A.name)]);expect(run.evidence.result).toBe('BLOCKED');expect(run.evidence.error_category).toBe('UNKNOWN_CREATE_OUTCOME');expect(mock.requests.filter(r=>r.method==='POST')).toHaveLength(1);});
 it('T02-11 429 remains observable and no automatic retry occurs',async()=>{const {run,mock}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name),{status:429,headers:{'Retry-After':'9','x-request-id':'rate-limit'},body:{error:'limited'}}]);expect(run.evidence.result).toBe('BLOCKED');expect(run.evidence.error_category).toBe('HTTP_429');expect(mock.send).toHaveBeenCalledTimes(2);expect(run.evidence.safe_response_headers['retry-after']).toBe('9');});
 it('T02-12 401/403 are BLOCKED provider/setup evidence',async()=>{const preflight=scripted([{status:401,body:{error:'auth'}}]);const result=await runP1T02Profiles({live:true,env,transport:preflight.transport});expect(result.result).toBe('BLOCKED');expect(result.preflight?.evidence.error_category).toBe('PROVIDER_AUTHORIZATION_BLOCKED');const create=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name),{status:403,body:{error:'forbidden'}}]);expect(create.run.evidence.result).toBe('BLOCKED');expect(create.run.evidence.error_category).toBe('PROVIDER_AUTHORIZATION_BLOCKED');});
 it('T02-13 API key sentinel never appears in output, errors, or evidence',async()=>{const mock=scripted([new Error(`network ${SENTINEL}`)]);const result=await runP1T02Profiles({live:true,env,transport:mock.transport});const text=JSON.stringify(result)+(result.preflight?.summary??'')+(result.preflight?.errorOutput??'')+(result.preflight?.machineReadableEvidence??'');expect(text).not.toContain(SENTINEL);expect(text).not.toContain(EXPECTED_EMAIL);});
 it('T02-14 Provider Request ID is captured when present',async()=>{const {run}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name,'profile-a'),list(P1_T02_PROFILE_A.name,'profile-a',{'x-request-id':'readback-id'})]);expect(run.evidence.provider_request_id).toBe('readback-id');});
 it('T02-15 unsafe response headers remain excluded',async()=>{const {run}=await profileRun(P1_T02_PROFILE_A,[list(P1_T02_PROFILE_A.name,'profile-a'),list(P1_T02_PROFILE_A.name,'profile-a',{'x-request-id':'safe','authorization':SENTINEL,'set-cookie':SENTINEL})]);expect(run.evidence.safe_response_headers).toEqual({'x-request-id':'safe'});expect(run.machineReadableEvidence).not.toContain(SENTINEL);});
 it('extra duplicate exact-name state blocks before POST',async()=>{const response={status:200,body:{profiles:[{_id:'one',name:P1_T02_PROFILE_A.name},{_id:'two',name:P1_T02_PROFILE_A.name}]}};const {run,mock}=await profileRun(P1_T02_PROFILE_A,[response]);expect(run.evidence.result).toBe('BLOCKED');expect(run.evidence.error_category).toBe('AMBIGUOUS_PROFILE_STATE');expect(mock.requests.filter(r=>r.method==='POST')).toHaveLength(0);});
 it('extra missing Profile ID blocks as malformed response',async()=>{const response={status:200,body:{profiles:[{name:P1_T02_PROFILE_A.name}]}};const {run}=await profileRun(P1_T02_PROFILE_A,[response]);expect(run.evidence.result).toBe('BLOCKED');expect(run.evidence.error_category).toBe('MALFORMED_PROVIDER_RESPONSE');});
 it('extra same A/B provider ID fails distinctness check',async()=>{const profiles=new Map<string,string>();const transport:ProviderTransport={kind:'live',send:async request=>{if(request.url==='/v1/auth/verify')return verified();if(request.method==='GET'&&request.url?.startsWith('/v1/profiles?name=')){const name=decodeURIComponent(request.url.split('=')[1]??'');return list(name,profiles.get(name));}if(request.method==='POST'){const body=request.body as {name:string};profiles.set(body.name,'same-id');return created(body.name,'same-id');}throw new Error('unexpected');}};const result=await runP1T02Profiles({live:true,env,transport});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('PROFILE_IDS_NOT_DISTINCT');});
});
