import { describe, expect, it, vi } from 'vitest';
import { createP1T02TeamPreflightCase, P1_T02_PROFILE_A, P1_T02_PROFILE_A_RECORDED_ID, P1_T02_PROFILE_B, P1_T02_PROFILE_B_RECORDED_ID, runP1T02F01Verification, runP1T02Profiles, runProviderSpikeCase, type ProviderTransport, type ProviderTransportRequest, type ProviderTransportResponse } from '../../src/provider-spike/index.js';

const API_KEY='P1T02F01_FAKE_API_KEY_SENTINEL';
const EXPECTED_EMAIL='trusted.operator@example.test';
const OTHER_EMAIL='other.team@example.test';
const env={ZERNIO_API_KEY:API_KEY,ZERNIO_EXPECTED_USER_EMAIL:EXPECTED_EMAIL};
function verify(email:unknown=EXPECTED_EMAIL):ProviderTransportResponse{return {status:200,headers:{'x-request-id':'verify-id'},body:{valid:true,userId:'fake-user',authType:'api_key',scope:null,email}};}
function profile(name:string,id:string,requestId:string):ProviderTransportResponse{return {status:200,headers:{'x-request-id':requestId},body:{profiles:[{_id:id,name}]}};}
function transport(responses:Array<ProviderTransportResponse|Error>){const requests:ProviderTransportRequest[]=[];const send=vi.fn(async(request:ProviderTransportRequest)=>{requests.push(request);const next=responses.shift();if(next instanceof Error)throw next;if(!next)throw new Error('unexpected transport call');return next;});return {transport:{kind:'live' as const,send},requests,send};}

describe('P1-T02-F01 trusted Zernio expected identity regressions',()=>{
 it('F01-T01 missing ZERNIO_EXPECTED_USER_EMAIL fails closed before transport',async()=>{const mock=transport([]);const result=await runP1T02F01Verification({live:true,env:{ZERNIO_API_KEY:API_KEY},transport:mock.transport});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('EXPECTED_PROVIDER_IDENTITY_MISSING');expect(mock.send).not.toHaveBeenCalled();});
 it('F01-T02 authenticated email mismatch blocks with zero mutations',async()=>{const mock=transport([verify(OTHER_EMAIL)]);const result=await runP1T02F01Verification({live:true,env,transport:mock.transport});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('PROVIDER_TARGET_IDENTITY_MISMATCH');expect(result.identity?.expectedIdentityMatch).toBe(false);expect(mock.requests).toHaveLength(1);expect(mock.requests.every(r=>r.method==='GET')).toBe(true);});
 it('F01-T03 authenticated email match passes identity preflight',async()=>{const mock=transport([verify(`  ${EXPECTED_EMAIL.toUpperCase()}  `)]);const box:{value:boolean|null}={value:null};const run=await runProviderSpikeCase(createP1T02TeamPreflightCase('live',EXPECTED_EMAIL,'mock',outcome=>{box.value=outcome.expectedIdentityMatch;}),{env,transport:mock.transport,redactionSecrets:[EXPECTED_EMAIL]});expect(run.evidence.result).toBe('PASS');expect(box.value).toBe(true);expect(mock.requests[0]?.url).toBe('/v1/auth/verify');});
 it('F01-T04 HTTP 200 from different authenticated identity is not authorization',async()=>{const mock=transport([verify(OTHER_EMAIL)]);const result=await runP1T02Profiles({live:true,env,transport:mock.transport});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('PROVIDER_TARGET_IDENTITY_MISMATCH');expect(mock.send).toHaveBeenCalledTimes(1);expect(mock.requests.filter(r=>r.url?.startsWith('/v1/profiles'))).toHaveLength(0);});
 it('F01-T05 missing or malformed provider email is BLOCKED malformed response',async()=>{for(const body of [{valid:true,userId:'fake-user'},{valid:true,email:'not-an-email'}]){const mock=transport([{status:200,body}]);const result=await runP1T02F01Verification({live:true,env,transport:mock.transport});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('MALFORMED_PROVIDER_RESPONSE');expect(mock.send).toHaveBeenCalledTimes(1);}});
 it('F01-T06 actual and expected email are absent from normal result/evidence output',async()=>{const mock=transport([verify(OTHER_EMAIL)]);const result=await runP1T02F01Verification({live:true,env,transport:mock.transport});const text=JSON.stringify(result)+(result.identityRun?.machineReadableEvidence??'')+(result.identityRun?.summary??'')+(result.identityRun?.errorOutput??'');expect(text).not.toContain(EXPECTED_EMAIL);expect(text).not.toContain(OTHER_EMAIL);});
 it('F01-T07 API key and expected email are redacted from errors/evidence',async()=>{const mock=transport([new Error(`network ${API_KEY} ${EXPECTED_EMAIL}`)]);const result=await runP1T02F01Verification({live:true,env,transport:mock.transport});const text=JSON.stringify(result)+(result.identityRun?.machineReadableEvidence??'')+(result.identityRun?.summary??'')+(result.identityRun?.errorOutput??'');expect(text).not.toContain(API_KEY);expect(text).not.toContain(EXPECTED_EMAIL);});
 it('F01-T08 verified identity permits read-only Profile A recorded-ID verification',async()=>{const mock=transport([verify(),profile(P1_T02_PROFILE_A.name,P1_T02_PROFILE_A_RECORDED_ID,'a-id'),profile(P1_T02_PROFILE_B.name,P1_T02_PROFILE_B_RECORDED_ID,'b-id')]);const result=await runP1T02F01Verification({live:true,env,transport:mock.transport});expect(result.result).toBe('PASS');expect(result.profileA?.outcome?.observedProfileId).toBe(P1_T02_PROFILE_A_RECORDED_ID);expect(result.profileA?.outcome?.profileIdMatch).toBe(true);expect(mock.requests.every(r=>r.method==='GET')).toBe(true);});
 it('F01-T09 verified identity permits read-only Profile B recorded-ID verification',async()=>{const mock=transport([verify(),profile(P1_T02_PROFILE_A.name,P1_T02_PROFILE_A_RECORDED_ID,'a-id'),profile(P1_T02_PROFILE_B.name,P1_T02_PROFILE_B_RECORDED_ID,'b-id')]);const result=await runP1T02F01Verification({live:true,env,transport:mock.transport});expect(result.result).toBe('PASS');expect(result.profileB?.outcome?.observedProfileId).toBe(P1_T02_PROFILE_B_RECORDED_ID);expect(result.profileB?.outcome?.profileIdMatch).toBe(true);expect(result.distinctProfileIds).toBe(true);});
 it('F01-T10 Profile ID mismatch fails closed with zero mutations',async()=>{const mock=transport([verify(),profile(P1_T02_PROFILE_A.name,'wrong-profile-id','a-wrong')]);const result=await runP1T02F01Verification({live:true,env,transport:mock.transport});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('PROVIDER_TARGET_PROFILE_ID_MISMATCH');expect(mock.requests).toHaveLength(2);expect(mock.requests.every(r=>r.method==='GET')).toBe(true);expect(result.profileB).toBeNull();});
 it('F01-T11 mutation-capable P1-T02 path cannot continue after identity mismatch',async()=>{const mock=transport([verify(OTHER_EMAIL)]);const result=await runP1T02Profiles({live:true,env,transport:mock.transport});expect(result.result).toBe('BLOCKED');expect(mock.requests.every(r=>r.method==='GET')).toBe(true);expect(mock.requests.filter(r=>['POST','PUT','PATCH','DELETE'].includes(r.method??'GET'))).toHaveLength(0);});
});
