import { describe, expect, it, vi } from 'vitest';
import { createP1T03IsolationCase, createP1T03KeyCreateCase, P1_T03_KEY_A, P1_T03_KEY_B, runP1T03, runProviderSpikeCase, type ProviderTransport, type ProviderTransportRequest, type ProviderTransportResponse } from '../../src/provider-spike/index.js';

const CONTROL='P1T03_CONTROL_SECRET_SENTINEL', EXPECTED_EMAIL='trusted.operator@example.invalid', EXPECTED_EMAIL_SENTINEL='P1T03_EXPECTED_EMAIL_SENTINEL@example.invalid';
const env={ZERNIO_API_KEY:CONTROL,ZERNIO_EXPECTED_USER_EMAIL:EXPECTED_EMAIL};
type ScenarioOptions={identityEmail?:string;malformedCreate?:'A'|'B';unknownCreate?:'A'|'B';orphanOnUnknown?:boolean;leak?:'A-foreign'|'B-foreign'|'A-unrelated'|'B-unrelated';cleanupFail?:'A'|'B';postRevokeStillValid?:'A'|'B';sameIds?:boolean;};
function profile(id:string,name:string){return {_id:id,name};}
function response(status:number,body:unknown={},id=`req-${Math.random().toString(16).slice(2)}`):ProviderTransportResponse{return {status,headers:{'x-request-id':id},body};}
function scenario(options:ScenarioOptions={}){
 const controlRequests:ProviderTransportRequest[]=[],scopedRequests:{logical:string;request:ProviderTransportRequest}[]=[],createdBodies:Record<string,unknown>={},keys=new Map<string,{logical:'A'|'B';id:string;name:string;profileId:string;secret:string;revoked:boolean}>();let createAttemptsA=0,createAttemptsB=0;
 const findById=(id:string)=>[...keys.values()].find(k=>k.id===id);
 const control:ProviderTransport={kind:'live',send:vi.fn(async request=>{controlRequests.push(request);if(request.method==='GET'&&request.url==='/v1/auth/verify')return response(200,{valid:true,email:options.identityEmail??EXPECTED_EMAIL},'identity-req');
  if(request.method==='POST'&&request.url==='/v1/api-keys'){const body=request.body as {name:string;profileIds:string[]};const logical:'A'|'B'=body.profileIds[0]===P1_T03_KEY_A.profileId?'A':'B';if(logical==='A')createAttemptsA++;else createAttemptsB++;createdBodies[logical]=body;const id=options.sameIds?'same-key-id':`key-${logical.toLowerCase()}`,secret=`P1T03_SCOPED_${logical}_SECRET_SENTINEL`;const key={logical,id,name:body.name,profileId:body.profileIds[0]!,secret,revoked:false};if(options.unknownCreate===logical){if(options.orphanOnUnknown)keys.set(secret,key);throw new Error('simulated network disconnect');}if(options.malformedCreate===logical){keys.set(secret,key);return response(201,{apiKey:{id,name:body.name,scope:'profiles',profileIds:[body.profileIds[0]],permission:'read',expiresAt:'2026-10-08T00:00:00Z'}},`create-${logical}`);}keys.set(secret,key);return response(201,{apiKey:{id,name:body.name,key:secret,scope:'profiles',profileIds:[profile(body.profileIds[0]!,logical==='A'?P1_T03_KEY_A.profileName:P1_T03_KEY_B.profileName)],permission:'read',expiresAt:'2026-10-08T00:00:00Z'}},`create-${logical}`);}
  if(request.method==='GET'&&request.url==='/v1/api-keys')return response(200,{apiKeys:[...keys.values()].filter(k=>!k.revoked).map(k=>({id:k.id,name:k.name,keyPreview:'[not-used]',scope:'profiles',profileIds:[k.profileId],permission:'read'}))},'list-keys');
  if(request.method==='DELETE'&&request.url?.startsWith('/v1/api-keys/')){const id=decodeURIComponent(request.url.split('/').at(-1)!);const key=findById(id);if(!key)return response(404,{error:'Not found'},`delete-${id}`);if(options.cleanupFail===key.logical)return response(500,{error:'cleanup fail'},`delete-${key.logical}`);key.revoked=true;return response(200,{message:'API key deleted successfully'},`delete-${key.logical}`);}throw new Error(`unexpected control request ${request.method} ${request.url}`);})};
 const scopedTransportFactory=(secret:string):ProviderTransport=>({kind:'live',send:vi.fn(async request=>{const key=keys.get(secret);if(!key)throw new Error('unknown scoped credential');scopedRequests.push({logical:key.logical,request});if(request.method==='GET'&&request.url==='/v1/auth/verify'){if(options.postRevokeStillValid===key.logical)return response(200,{valid:true},`verify-${key.logical}`);return key.revoked?response(401,{error:'Unauthorized'},`verify-${key.logical}`):response(200,{valid:true},`verify-${key.logical}`);}
  if(key.revoked)return response(401,{error:'Unauthorized'},`revoked-${key.logical}`);const own=key.logical==='A'?P1_T03_KEY_A:P1_T03_KEY_B,foreign=key.logical==='A'?P1_T03_KEY_B:P1_T03_KEY_A;if(request.method==='GET'&&request.url==='/v1/profiles'){let profiles=[profile(own.profileId,own.profileName)];if(options.leak===`${key.logical}-foreign`)profiles.push(profile(foreign.profileId,foreign.profileName));if(options.leak===`${key.logical}-unrelated`)profiles.push(profile('ffffffffffffffffffffffff','unrelated-profile'));return response(200,{profiles},`list-${key.logical}`);}if(request.method==='GET'&&request.url?.includes('?name=')){const name=decodeURIComponent(request.url.split('?name=')[1]??'');if(name===own.profileName)return response(200,{profiles:[profile(own.profileId,own.profileName)]},`own-${key.logical}`);if(name===foreign.profileName){const leak=options.leak===`${key.logical}-foreign`;return response(200,{profiles:leak?[profile(foreign.profileId,foreign.profileName)]:[]},`cross-${key.logical}`);}return response(200,{profiles:[]},`other-${key.logical}`);}throw new Error(`unexpected scoped request ${request.method} ${request.url}`);})});
 return {control,scopedTransportFactory,controlRequests,scopedRequests,createdBodies,keys,get createAttemptsA(){return createAttemptsA;},get createAttemptsB(){return createAttemptsB;}};
}

function run(options:ScenarioOptions={},extra:Partial<Parameters<typeof runP1T03>[0]>={}){const s=scenario(options);return runP1T03({live:true,env,controlTransport:s.control,scopedTransportFactory:s.scopedTransportFactory,runTag:'offline-test-run',...extra}).then(result=>({result,s}));}

describe('P1-T03 scoped API key isolation offline regressions',()=>{
 it('T03-01 default execution is offline and performs zero external requests',async()=>{const send=vi.fn();const result=await runP1T03({controlTransport:{kind:'live',send} as ProviderTransport});expect(result.errorCategory).toBe('LIVE_OPT_IN_REQUIRED');expect(send).not.toHaveBeenCalled();});
 it('T03-02 missing control-plane credential blocks before mutation',async()=>{const s=scenario();const result=await runP1T03({live:true,env:{ZERNIO_EXPECTED_USER_EMAIL:EXPECTED_EMAIL},controlTransport:s.control,scopedTransportFactory:s.scopedTransportFactory});expect(result.result).toBe('BLOCKED');expect(result.preflight?.evidence.error_category).toBe('MISSING_LIVE_CREDENTIAL');expect(s.controlRequests).toHaveLength(0);});
 it('T03-03 missing trusted expected identity blocks before mutation',async()=>{const s=scenario();const result=await runP1T03({live:true,env:{ZERNIO_API_KEY:CONTROL},controlTransport:s.control,scopedTransportFactory:s.scopedTransportFactory});expect(result.result).toBe('BLOCKED');expect(result.preflight?.evidence.error_category).toBe('EXPECTED_PROVIDER_IDENTITY_MISSING');expect(s.controlRequests).toHaveLength(0);});
 it('T03-04 control-plane identity mismatch blocks before scoped-key creation',async()=>{const {result,s}=await run({identityEmail:'different@example.invalid'});expect(result.result).toBe('BLOCKED');expect(result.preflight?.evidence.error_category).toBe('PROVIDER_TARGET_IDENTITY_MISMATCH');expect(s.controlRequests.filter(r=>r.method==='POST')).toHaveLength(0);});
 it('T03-05 Key A creation body has exact read-only Profile A scope and bounded expiry',async()=>{const {result,s}=await run();expect(result.result).toBe('PASS');expect(s.createdBodies.A).toMatchObject({scope:'profiles',profileIds:[P1_T03_KEY_A.profileId],permission:'read',expiresIn:1});expect((s.createdBodies.A as {profileIds:string[]}).profileIds).toEqual([P1_T03_KEY_A.profileId]);});
 it('T03-06 Key B creation body has exact read-only Profile B scope and bounded expiry',async()=>{const {result,s}=await run();expect(result.result).toBe('PASS');expect(s.createdBodies.B).toMatchObject({scope:'profiles',profileIds:[P1_T03_KEY_B.profileId],permission:'read',expiresIn:1});expect((s.createdBodies.B as {profileIds:string[]}).profileIds).toEqual([P1_T03_KEY_B.profileId]);});
 it('T03-07 scoped key values never appear in result/evidence/errors',async()=>{const {result}=await run();const text=JSON.stringify(result);expect(text).not.toContain('P1T03_SCOPED_A_SECRET_SENTINEL');expect(text).not.toContain('P1T03_SCOPED_B_SECRET_SENTINEL');expect(text).not.toContain(CONTROL);expect(text).not.toContain(EXPECTED_EMAIL);});
 it('T03-08 malformed create response missing key value fails closed and revokes returned key ID',async()=>{const {result,s}=await run({malformedCreate:'A'});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('MALFORMED_PROVIDER_RESPONSE');expect(s.scopedRequests).toHaveLength(0);expect(s.controlRequests.some(r=>r.method==='DELETE'&&r.url==='/v1/api-keys/key-a')).toBe(true);});
 it('T03-09 Key A visible list contains only Profile A',async()=>{const {result}=await run();expect(result.isolationA?.fullVisibleProfileCount).toBe(1);expect(result.isolationA?.ownProfileVisible).toBe(true);expect(result.isolationA?.foreignProfileVisible).toBe(false);});
 it('T03-10 Key A own exact-name lookup returns recorded A ID',async()=>{const {result}=await run();expect(result.isolationA?.ownExactMatch).toBe(true);expect(result.keyA?.permittedProfileId).toBe(P1_T03_KEY_A.profileId);});
 it('T03-11 Key A cross-name lookup cannot expose Profile B',async()=>{const {result}=await run();expect(result.isolationA?.crossLookupIsolated).toBe(true);expect(result.isolationA?.foreignProfileVisible).toBe(false);});
 it('T03-12 Key B visible list contains only Profile B',async()=>{const {result}=await run();expect(result.isolationB?.fullVisibleProfileCount).toBe(1);expect(result.isolationB?.ownProfileVisible).toBe(true);expect(result.isolationB?.foreignProfileVisible).toBe(false);});
 it('T03-13 Key B own exact-name lookup returns recorded B ID',async()=>{const {result}=await run();expect(result.isolationB?.ownExactMatch).toBe(true);expect(result.keyB?.permittedProfileId).toBe(P1_T03_KEY_B.profileId);});
 it('T03-14 Key B cross-name lookup cannot expose Profile A',async()=>{const {result}=await run();expect(result.isolationB?.crossLookupIsolated).toBe(true);expect(result.isolationB?.foreignProfileVisible).toBe(false);});
 it('T03-15 unrelated Profile exposure produces critical FAIL and cleanup',async()=>{const {result}=await run({leak:'A-unrelated'});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_CROSS_PROFILE_SCOPE_LEAKAGE');expect(result.crossProfileLeakageObserved).toBe(true);expect(result.cleanup.every(x=>x.confirmed)).toBe(true);expect(result.isolationB).toBeNull();});
 it('T03-16 ambiguous API-key creation is never blindly retried',async()=>{const {result,s}=await run({unknownCreate:'A'});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('UNKNOWN_SCOPED_KEY_CREATE_OUTCOME');expect(s.createAttemptsA).toBe(1);expect(s.controlRequests.filter(r=>r.method==='GET'&&r.url==='/v1/api-keys')).toHaveLength(1);});
 it('T03-17 orphaned ambiguous create is reconciled and revoked without secret reuse',async()=>{const {result,s}=await run({unknownCreate:'A',orphanOnUnknown:true});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('UNKNOWN_SCOPED_KEY_CREATE_OUTCOME');expect(s.controlRequests.some(r=>r.method==='DELETE'&&r.url==='/v1/api-keys/key-a')).toBe(true);expect(s.scopedRequests).toHaveLength(0);});
 it('T03-18 cleanup executes after partial isolation failure once keys exist',async()=>{const {result,s}=await run({leak:'A-foreign'});expect(result.result).toBe('FAIL');expect(s.controlRequests.filter(r=>r.method==='DELETE')).toHaveLength(2);expect(result.cleanup).toHaveLength(2);expect(result.isolationB).toBeNull();});
 it('T03-19 successful revocation is followed by rejected authentication',async()=>{const {result}=await run();expect(result.result).toBe('PASS');expect(result.cleanup).toHaveLength(2);expect(result.cleanup.every(x=>x.confirmed&&x.postRevokeCredentialValid===false&&x.verifyStatus===401)).toBe(true);});
 it('T03-20 cleanup-not-confirmed prevents PASS',async()=>{const {result}=await run({cleanupFail:'B',postRevokeStillValid:'B'});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('SCOPED_KEY_CLEANUP_UNCONFIRMED');expect(result.cleanup.find(x=>x.logicalKey==='B')?.confirmed).toBe(false);});
 it('T03-21 aggregate request ceiling blocks excess calls',async()=>{const {result}=await run({}, {requestCeiling:5});expect(result.result).toBe('BLOCKED');expect(result.liveRequestCount).toBeLessThanOrEqual(5);expect(result.errorCategory).toBe('SCOPED_KEY_CLEANUP_UNCONFIRMED');});
 it('T03-22 existing suites remain compatible and normal run uses 13 calls',async()=>{const {result}=await run();expect(result.result).toBe('PASS');expect(result.liveRequestCount).toBe(13);expect(result.keyA?.providerKeyId).not.toBe(result.keyB?.providerKeyId);});
 it('extra cross-Profile foreign exposure is critical leakage',async()=>{const {result}=await run({leak:'B-foreign'});expect(result.result).toBe('FAIL');expect(result.errorCategory).toBe('CRITICAL_CROSS_PROFILE_SCOPE_LEAKAGE');expect(result.crossProfileLeakageObserved).toBe(true);});
 it('extra same provider key IDs fail closed when cleanup cannot be confirmed',async()=>{const {result}=await run({sameIds:true});expect(result.result).toBe('BLOCKED');expect(result.errorCategory).toBe('SCOPED_KEY_CLEANUP_UNCONFIRMED');expect(result.cleanup.length).toBeGreaterThan(0);});
 it('extra expected identity secret is redacted from preflight evidence',async()=>{const s=scenario({identityEmail:EXPECTED_EMAIL_SENTINEL});const result=await runP1T03({live:true,env:{ZERNIO_API_KEY:CONTROL,ZERNIO_EXPECTED_USER_EMAIL:EXPECTED_EMAIL_SENTINEL},controlTransport:s.control,scopedTransportFactory:s.scopedTransportFactory,runTag:'redaction'});const text=JSON.stringify(result)+String(result.preflight?.machineReadableEvidence)+String(result.preflight?.errorOutput);expect(text).not.toContain(EXPECTED_EMAIL_SENTINEL);});
 it('extra scoped transport error redacts raw scoped secret',async()=>{const secret='P1T03_DIRECT_SCOPED_SECRET';const transport:ProviderTransport={kind:'live',send:async()=>{throw new Error(`network ${secret}`);}};const run=await runProviderSpikeCase(createP1T03IsolationCase(P1_T03_KEY_A,P1_T03_KEY_B),{env:{P1_T03_SCOPED_KEY_RUNTIME:secret},transport,redactionSecrets:[secret]});const text=run.summary+run.machineReadableEvidence+String(run.errorOutput);expect(text).not.toContain(secret);});
 it('extra direct create case never serializes returned key secret',async()=>{const secret='P1T03_DIRECT_CREATE_SECRET';const transport:ProviderTransport={kind:'live',send:async request=>response(201,{apiKey:{id:'direct-key',name:(request.body as {name:string}).name,key:secret,scope:'profiles',profileIds:[P1_T03_KEY_A.profileId],permission:'read',expiresAt:'2026-10-08T00:00:00Z'}},'direct-create')};const test=createP1T03KeyCreateCase(P1_T03_KEY_A,'aimm-p1-t03-profile-a-readonly-direct');const result=await runProviderSpikeCase(test,{env:{ZERNIO_API_KEY:CONTROL},transport});expect(result.evidence.result).toBe('PASS');expect(result.machineReadableEvidence).not.toContain(secret);});
});
