import { readFileSync } from 'node:fs';
import { describe, expect, it, vi } from 'vitest';
import {
  P1_T04_PROFILE_ID,
  probeP1T05VpsReceiverHttps,
  runAfterP1T05ExternalReceiverReadiness,
  runP1T05,
  startP1T05Receiver,
  type P1T05ReceiverController,
  type ProviderTransport,
  type ProviderTransportRequest,
  type ProviderTransportResponse,
} from '../../src/provider-spike/index.js';

const RECEIVER_URL='https://vps.example.invalid/internal-provider-spike/p1-t05',MARKER='p1-t05-f02-marker';
const CONTROL='P1T05F02_CONTROL_SENTINEL',SECRET='P1T05F02_WEBHOOK_SECRET_SENTINEL',EMAIL='p1t05f02@example.invalid',RUN='f02-test';
const env={ZERNIO_API_KEY:CONTROL,ZERNIO_EXPECTED_USER_EMAIL:EMAIL};
function readinessResponse(status:number,marker:string|undefined=MARKER,headers:Record<string,string>={}){return new Response('',{status,headers:{...(marker?{'x-aimm-p1-t05-receiver':marker}:{}),...headers}});}
function fakeReceiver(waitForReadiness:P1T05ReceiverController['waitForReadiness'],snapshot:()=>ReturnType<P1T05ReceiverController['snapshot']>):P1T05ReceiverController{const base:P1T05ReceiverController={port:1,localUrl:'http://127.0.0.1:1/internal-provider-spike/p1-t05',snapshot,waitForTest:async()=>null,waitForReal:async()=>[],close:async()=>{}};return waitForReadiness?{...base,waitForReadiness}:base;}
function rsp(status:number,body:unknown={},id='req'):ProviderTransportResponse{return{status,headers:{'x-request-id':id},body};}
function failedWebhookScenario(){const requests:ProviderTransportRequest[]=[];let webhook=true;const name=`aimm-p1-t05-webhook-${RUN}`;const transport:ProviderTransport={kind:'live',send:vi.fn(async r=>{requests.push(r);if(r.method==='GET'&&r.url==='/v1/auth/verify')return rsp(200,{valid:true,email:EMAIL},'identity');if(r.method==='POST'&&r.url==='/v1/webhooks/settings'){const b=r.body as any;return rsp(200,{webhook:{_id:'wh-f02',name:b.name,url:b.url,events:b.events,isActive:true,profileIds:b.profileIds}},'create');}if(r.method==='GET'&&r.url==='/v1/webhooks/settings')return rsp(200,{webhooks:webhook?[{_id:'wh-f02',name,url:RECEIVER_URL,events:['post.scheduled'],isActive:true,profileIds:[P1_T04_PROFILE_ID]}]:[]},'list');if(r.method==='POST'&&r.url==='/v1/webhooks/test')return rsp(500,{error:'blocked'},'test');if(r.method==='GET'&&r.url?.startsWith('/v1/webhooks/logs?'))return rsp(200,{logs:[]},'logs');if(r.method==='DELETE'&&r.url?.startsWith('/v1/webhooks/settings?webhookId=')){webhook=false;return rsp(200,{success:true},'delete');}throw new Error(`unexpected ${r.method} ${r.url}`);})};return{requests,transport};}

describe('P1-T05-F02 VPS HTTPS receiver regressions',()=>{
 it('F02-T01 confirmed external readiness must occur before provider callback executes',async()=>{let confirmed=0;let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});const receiver=fakeReceiver(async()=>{await gate;confirmed=1;return true;},()=>({deliveries:[],testDeliveries:0,realDeliveries:0,logicalUniqueRealEvents:0,foreignProfileObserved:false,profileAttributionUnconfirmed:false,readinessHits:1,readinessConfirmedHits:confirmed}));const provider=vi.fn(async()=> 'ran');const pending=runAfterP1T05ExternalReceiverReadiness(receiver,provider,{baselineHits:0,timeoutMs:100});await Promise.resolve();expect(provider).not.toHaveBeenCalled();release();await expect(pending).resolves.toEqual({ready:true,value:'ran',readinessHits:1});expect(provider).toHaveBeenCalledTimes(1);});
 it('F02-T02 exact receiver 401 plus marker and confirmation allows provider execution',async()=>{const receiver=await startP1T05Receiver({secret:SECRET,expectedProfileId:P1_T04_PROFILE_ID,expectedAccountId:'acct',expectedContentMarker:'marker',path:'/internal-provider-spike/p1-t05',readinessMarker:MARKER});try{const first=await fetch(receiver.localUrl,{method:'POST',headers:{'x-aimm-p1-t05-readiness':MARKER}}),second=await fetch(receiver.localUrl,{method:'POST',headers:{'x-aimm-p1-t05-readiness-confirmed':MARKER}});expect(first.status).toBe(401);expect(first.headers.get('x-aimm-p1-t05-receiver')).toBe(MARKER);expect(second.status).toBe(401);expect(receiver.snapshot()).toMatchObject({readinessHits:1,readinessConfirmedHits:1});const provider=vi.fn(async()=>true);const gated=await runAfterP1T05ExternalReceiverReadiness(receiver,provider,{baselineHits:0,timeoutMs:10});expect(gated.ready).toBe(true);expect(provider).toHaveBeenCalledTimes(1);const fetcher=vi.fn().mockResolvedValueOnce(readinessResponse(401)).mockResolvedValueOnce(readinessResponse(401));const evidence=await probeP1T05VpsReceiverHttps(RECEIVER_URL,MARKER,{fetcher});expect(evidence).toMatchObject({ready:true,httpStatus:401,tlsSuccess:true,receiverMarkerMatch:true,receiverConfirmed:true,redirected:false,errorCategory:null});}finally{await receiver.close();}});
 it('F02-T03 404 readiness response blocks',async()=>{const fetcher=vi.fn().mockResolvedValue(readinessResponse(404)),provider=vi.fn();const evidence=await probeP1T05VpsReceiverHttps(RECEIVER_URL,MARKER,{fetcher});if(evidence.ready)provider();expect(evidence).toMatchObject({ready:false,httpStatus:404,errorCategory:'VPS_READINESS_STATUS_UNEXPECTED'});expect(provider).not.toHaveBeenCalled();expect(fetcher).toHaveBeenCalledTimes(1);});
 it('F02-T04 502 and 503 readiness responses block',async()=>{for(const status of [502,503]){const fetcher=vi.fn().mockResolvedValue(readinessResponse(status)),provider=vi.fn();const evidence=await probeP1T05VpsReceiverHttps(RECEIVER_URL,MARKER,{fetcher});if(evidence.ready)provider();expect(evidence.ready).toBe(false);expect(evidence.httpStatus).toBe(status);expect(provider).not.toHaveBeenCalled();expect(fetcher).toHaveBeenCalledTimes(1);}});
 it('F02-T05 redirected readiness is not exact endpoint PASS',async()=>{const fetcher=vi.fn().mockResolvedValue(readinessResponse(302,MARKER,{location:'https://other.example.invalid/'})),provider=vi.fn();const evidence=await probeP1T05VpsReceiverHttps(RECEIVER_URL,MARKER,{fetcher});if(evidence.ready)provider();expect(evidence).toMatchObject({ready:false,redirected:true,errorCategory:'VPS_READINESS_REDIRECTED'});expect(provider).not.toHaveBeenCalled();expect(fetcher.mock.calls[0]?.[1]).toMatchObject({redirect:'manual'});});
 it('F02-T06 TLS or network readiness failure blocks',async()=>{const fetcher=vi.fn(async()=>{throw new TypeError('fetch failed');}),provider=vi.fn();const evidence=await probeP1T05VpsReceiverHttps(RECEIVER_URL,MARKER,{fetcher});if(evidence.ready)provider();expect(evidence).toMatchObject({ready:false,tlsSuccess:false,errorCategory:'VPS_READINESS_TLS_OR_NETWORK_FAILURE'});expect(provider).not.toHaveBeenCalled();});
 it('F02-T07 401 from wrong handler cannot PASS',async()=>{const fetcher=vi.fn().mockResolvedValue(readinessResponse(401,'wrong-handler')),provider=vi.fn();const evidence=await probeP1T05VpsReceiverHttps(RECEIVER_URL,MARKER,{fetcher});if(evidence.ready)provider();expect(evidence).toMatchObject({ready:false,httpStatus:401,receiverMarkerMatch:false,errorCategory:'VPS_READINESS_WRONG_HANDLER'});expect(provider).not.toHaveBeenCalled();expect(fetcher).toHaveBeenCalledTimes(1);});
 it('F02-T08 F02 live path has no Railway or Quick Tunnel dependency',()=>{const runner=readFileSync(new URL('../../src/provider-spike/p1-t05-f02-runner.ts',import.meta.url),'utf8'),probe=readFileSync(new URL('../../src/provider-spike/p1-t05-f02-probe.ts',import.meta.url),'utf8');expect(`${runner}\n${probe}`).not.toMatch(/railway|cloudflare|trycloudflare|ngrok|webhook\.site|render|vercel/i);});
 it('F02-T09 webhook.test remains maximum one POST',async()=>{const s=failedWebhookScenario(),receiver=fakeReceiver(undefined,()=>({deliveries:[],testDeliveries:0,realDeliveries:0,logicalUniqueRealEvents:0,foreignProfileObserved:false,profileAttributionUnconfirmed:false}));await runP1T05({live:true,env,controlTransport:s.transport,receiver,receiverUrl:RECEIVER_URL,webhookSecret:SECRET,runTag:RUN});expect(s.requests.filter(r=>r.method==='POST'&&r.url==='/v1/webhooks/test')).toHaveLength(1);});
 it('F02-T10 accepted P1-T05-F01 diagnostic inventory remains 13 tests',()=>{const text=readFileSync(new URL('./p1-t05-f01.test.ts',import.meta.url),'utf8');expect((text.match(/\bit\('/g)??[])).toHaveLength(13);expect(text).toContain('WEBHOOK_TEST_FAILURE_DIAGNOSTICS_UNAVAILABLE');});
 it('F02-T11 accepted parent P1-T05 regression inventory remains 46 tests',()=>{const text=readFileSync(new URL('./p1-t05.test.ts',import.meta.url),'utf8');expect((text.match(/\bit\('/g)??[])).toHaveLength(46);});
 it('F02-T12 full historical suite gate remains the unfiltered npm test command',()=>{const pkg=JSON.parse(readFileSync(new URL('../../package.json',import.meta.url),'utf8')) as {scripts?:Record<string,string>};expect(pkg.scripts?.test).toBe('vitest run --reporter=verbose');});
});
